### ISSUE TITLE
How to configure org-noter to be compatible with org-roam

### ISSUE THREAD

**Issue by rishubn** [weirdNox/org-noter#102]
Hi,

Org-roam requires a "#+Title" at the top of the org file. I see that org-noter creates new note files with the heading "* PDF title".

Is it possible to change the heading token from a "*" to a "#+Title"

**Comment by weikai-chen** [comment]
@shrub77 I find  [org-roam-bibtex](https://github.com/org-roam/org-roam-bibtex#modifying-templates) helpful.
