### ISSUE TITLE
org-noter appears to be hostile to soft-wrapped prose

### ISSUE THREAD

**Issue by JonathanReeve** [weirdNox/org-noter#103]
Every so often, org-noter will disable my truncate-lines and visual-line-navigation settings in Spacemacs, making it so that soft-wrapped lines of prose are truncated. I can re-disable truncate-lines, but org-noter will keep re-enabling it.

**Comment by benisjammin** [comment]
The snippet in #44 might help.

**Comment by JonathanReeve** [comment]
For some reason this has fixed itself, at least according to the Doom defaults. So I'll close this, especially since #44 seems to be where this discussion is happening.
