### ISSUE TITLE
Just notes: no document notes

### ISSUE THREAD

**Issue by Chobbes** [weirdNox/org-noter#11]
Hi!

I have a bit of a silly problem. Sometimes I can't get a PDF for a book, and have to get a dead-tree version. But I still like keeping my notes in org mode, and I like being able to flip pages in the notes.

So, I'm wondering if we can have notes where I can easily increment the page number, but not have a corresponding document, if that makes any sense! That way I can keep notes for PDFs in exactly the same way as I keep notes for physical books.

**Comment by weirdNox** [comment]
Hm, it could be done, but with some hacks, because currently the session depends on the PDF buffer to exist. It would be almost like only having `org-noter-sync-*-note` commands, right? 

It doesn't look like a great upgrade from Org-mode itself though, because you would lose all the shortcuts and scroll sync, and would be more like having plain headlines which you already have with Org-mode :P

**Comment by Chobbes** [comment]
Fair points. It's a bit of a weird desire, but I figured I'd bring it up :). Maybe somebody has better ideas too.

Mostly I want to be able to create the headings automatically, but maybe I should just write some elisp for that. I'm also considering making a giant 1000 page blank PDF so I can just have exactly the same workflow with a paper copy of a book. I know that probably seems a little strange, but I don't want to have to think about it being any different!

**Comment by weirdNox** [comment]
I also thought about the 1000 page blank PDF :P It looks like it would be the closest to what you want, keeping it really 1-to-1 on the dead tree books.

Maybe it would be a bit awkward to have a white pane on the left no? Maybe creating the PDF with big letters saying what page it is would be the best in that case, at least you wouldn't get lost :P

**Comment by weirdNox** [comment]
Hey there! I hope you arrived at a solution to your problem in the meantime :P I'm closing this for now, reopen it if you have more ideas :)
