### ISSUE TITLE
can't save pdf annotaions when NOTER_DOCUMENT is a symlink path

### ISSUE THREAD

**Issue by ghost** [weirdNox/org-noter#117]
When the :NOTER_DOCUMENT: in the org-noter note file is a symlink path, any annotation created with pdf-tools will lost on the next file open, ie the annotation are not actually saved during the org-noter session.
pdf-tools alone have no problems with symlink path.

I currently use a pdf library folder that syncing between a windows box and linux box, and use org-roam-bibtex to edit org-noter notes, symlink is necessary if I want to use the same path for NOTER_DOCUMENT on both system

**Comment by ghost** [comment]
Set `directory-abbrev-alist' will solve this bug, so this is nothing to do with org-noter then?

**Comment by Jonghyun-Yun** [comment]
> Set `directory-abbrev-alist' will solve this bug, so this is nothing to do with org-noter then?

Could you please elaborate how you resolve it? I am experiencing the same issue.

**Comment by ghost** [comment]
suppose you have a symlink `/aaa` pointing to a folder `/AAA/`

```emacs-lisp
(setq directory-abbrev-alist
        '(("/aaa" . "~/AAA")))
````
However since emacs have functions like `true-path`,  this may not be the correct fix.  
In my case it turned out one of my package org-roam-bibtex failed to pass the true path of 
pdf files to org-noter, which was [fixed ](https://github.com/org-roam/org-roam/issues/1063)

**Comment by Jonghyun-Yun** [comment]
> suppose you have a symlink `/aaa` pointing to a folder `/AAA/`
> 
> ```emacs-lisp
> (setq directory-abbrev-alist
>         '(("/aaa" . "~/AAA")))
> ```
> 
> However since emacs have functions like `true-path`, this may not be the correct fix.
> In my case it turned out one of my package org-roam-bibtex failed to pass the true path of
> pdf files to org-noter, which was [fixed ](https://github.com/org-roam/org-roam/issues/1063)

Thanks a lot. Using `file-truename` seems to solve my issue https://github.com/weirdNox/org-noter/issues/144#issue-871459193
