### ISSUE TITLE
Invalid or no document property found

### ISSUE THREAD

**Issue by jcguu95** [weirdNox/org-noter#119]
Setting the search path to `(setq org-noter-notes-search-path '("~/+NOTES/wiki/literature"))` and run `org-noter` in a pdf file leads to an error `"Invalid or no document property found. Please specify a document path: "` with a prompt asking me which path to provide. I choose the same path and it still gives an error.

The path `~/+NOTES/wiki/literature` exists in my file system. It is a symlink to `~/.+PLUGS/Dropbox/FILE-SYSTEM/+NOTES/wiki/literature`. For testing, I have done the following.

1. Change the path to `"~/test"`. `org-noter` works as expected.
2. Change the path to `~/+test`. `org-noter` works as expected.
3. Symlink `"~/+test"` to `~/sltest`, and change the path to it. `org-noter` works as expected.

So.. I cannot really tell what's wrong is the path `~/+NOTES/wiki/literature`..

**Comment by AtomicNess123** [comment]
Did you fix this problem?

**Comment by jcguu95** [comment]
I didn't keep using `org-noter`, so.. no(t yet).

**Comment by AtomicNess123** [comment]
What are you using now, if I'm not too curious?

**Comment by jcguu95** [comment]
I'm not using anything at all as a replacement. I plan to pick `org-noter` back in near future, however.

**Comment by jcguu95** [comment]
I ran the same thing after months. It seems that the problem has been fixed.
