### ISSUE TITLE
Empty lines

### ISSUE THREAD

**Issue by Nebucatnetzer** [weirdNox/org-noter#12]
It would be great to have an option for inserting empty lines before and after the heading.
I write my documents this way to easily spot which headings contain content and which are still empty.

E.g. like so
```

* Test heading

Some content.

** Sub Heading without content

** Sub heading with content
```

Some more content.

This would then fold like this:
```

* Test Heading...

** Sub Heading without content...
** Sub Heading with content...
```

**Comment by weirdNox** [comment]
Hey!

At the moment, org-noter uses `org-insert-heading`, which will keep the heading separated by an empty line if the previous headline follows that structure. 

For example, if we have the following setup:
```
* First page
:PROPERTIES:
:NOTER_PAGE: 1
:END:
Content followed by newline

* Second page
:PROPERTIES:
:NOTER_PAGE: 2
:END:
```

Creating a note on page 3 would create a newline after the note on page two, even if it was empty.

I'm not sure I understood what you proposed, maybe you could expand on it?

**Comment by Nebucatnetzer** [comment]
I write my notes like this:

```
* First page
:PROPERTIES:
:NOTER_PAGE: 1
:END:

Content with a newline before the content and followed by newline

* Second page
:PROPERTIES:
:NOTER_PAGE: 2
:END:
```

**Comment by weirdNox** [comment]
Oh, so the only thing missing is the line before the note itself?

**Comment by Nebucatnetzer** [comment]
Hehe now that you say it like this. Yeah I guess that's it :smile:

**Comment by weirdNox** [comment]
When the update gets to MELPA, try setting `org-noter-separate-notes-from-heading` to t, and see if it works :)

**Comment by Nebucatnetzer** [comment]
Thanks a ton! Works perfectly :muscle:

**Comment by weirdNox** [comment]
Glad I could help :)
