### ISSUE TITLE
Integration with pdf-tools' annotation support?

### ISSUE THREAD

**Issue by 4lex1v** [weirdNox/org-noter#13]
Is it possible to keep annotations like highlights in sync with the notes? It would be a convenient way to review existing annotations from the notes and avoid duplication of those?

**Comment by weirdNox** [comment]
Hello there! I'm sorry, I have not used PDF annotations before besides the eventual cross out, so could you explain what you mean by keeping them in sync? Aren't they already "in sync" with the PDF itself?

**Comment by 4lex1v** [comment]
Hey! Thanks for taking a look into this. I'm not sure if it's something possible, but my approach to reading is that I highlight main ideas on the first pass, during the second pass I can focus on these and later use as main points while revising the chapter in my head. Having these excerpts auto-synched with org-noter's notes would allow to have a quick and easy access to the highlights. 

Also sometimes I'd add notes to the highlights with some thoughts, this is something that could be done with pdf-tools for emacs, but I'd definitely prefer org-noter for this.

**Comment by weirdNox** [comment]
Ohh, that's interesting! So, if I understood correctly, you would create some highlights in the document, and then run a command which would import them into the notes. If that's what you want, then it should be similar very similar to the already existing `org-noter-create-skeleton`, which imports the outline into the document.

Doing that, maybe I could even offer the possibility of removing the highlights after that (if the user wants), and it should check whether or not that annotation is already imported to prevent having copies of the same thing!

**Comment by Cumol** [comment]
I will piggyback onto this. As "precise notes" already exist, I wonder if one could combine the highlighting offered by pdf-tools with org-noter's precise notes. The moment a highlight is made, it also invokes precise note and the output is combined.

**Comment by weirdNox** [comment]
I think this should be working right now (well, when MELPA receives the update) with `org-noter-create-skeleton`. Give it a try! :)

Also, I only added support for highlights, underlines, links, squigglies, text notes, and strikeouts. If you want support for more, write a comment here so I know it exists in the first place! :P

**Comment by bepolymathe** [comment]
Hi, 

This function is great. I just feel like it doesn't extract the highlighted or underlined passages correctly. The beginning of the passage is often missing. Do you have the same problem?
