### ISSUE TITLE
Running org-noter Inside a heading in an Org notes file

### ISSUE THREAD

**Issue by AtomicNess123** [weirdNox/org-noter#132]
Hi, excellent package.
I tried to use it within an org file, below a heading, but it wouldn't work.
Does there need to be a specific property below the heading?
`I get the error: "Invalid or no document property found"`

**Comment by auroranil** [comment]
> `I get the error: "Invalid or no document property found"`

I can only find one instance of the error you mentioned above, and it has more to its message:
https://github.com/weirdNox/org-noter/blob/d051a5909878e2214422fd275968ab4d7ef9bcab/org-noter.el#L1295-L1297

The README file explains that you will need to choose a document to attach your notes with. 
> * Run M-x org-noter inside! On the first run, *it will ask you for the path of the document and save it in a property*. By default, it will also let you annotate an attached file (org-attach documentation).

https://github.com/weirdNox/org-noter#usage

Alternatively you can set `:NOTER_DOCUMENT:` property directly under heading with value that points to your document. 

I do find the error confusing though. Would it better if the message was split between property not found and file not found, depending on which scenario it finds itself in.

**Comment by AtomicNess123** [comment]
One question though! (I closed it too fast)! Is it possible to have a ORG document as the document you want to take notes for? I believe org-noter only works with DOC and PDF.

**Comment by auroranil** [comment]
No unfortunately.

A workaround would be to link to that ORG file, which is what org-mode itself can do. You can also link to particular sections: https://orgmode.org/guide/Hyperlinks.html

> File links can contain additional information to make Emacs jump to a particular location in the file when following a link. This can be a line number or a search option after a double colon.

**Comment by auroranil** [comment]
Even better solution: https://github.com/nobiot/org-transclusion

**Comment by auroranil** [comment]
Better solution: https://github.com/nobiot/org-transclusion
