### ISSUE TITLE
Epub global search, is it possible?

### ISSUE THREAD

**Issue by santiyounger** [weirdNox/org-noter#138]
Hey
I love org-noter and it's super powerful. I'm just stuck with the following problem.

I can't figure out is how to do a global search on an epub book.

I have highlights saved from my kindle, and now I want to search specific quotes  globally in the book, so that I can take note on the,  but all I'm able to do is search withing specific chapters.

Is there a way to run a global search throughout the whole book?

---

I'm not sure if this is a limitation of nov-el or if for some reason it's not possible. Would really appreciate any suggestions

## specs 
I'm using spacemacs in Garuda Linux
I'm not sure what info is necessary so feel free to let me know if I need to provide more info

Thanks a lot

**Comment by Charlie-Gordon** [comment]
Unfortunately, this is the limitation of nov.el. See the [todo list](https://depp.brause.cc/nov.el/TODO.org) on its [repository](https://depp.brause.cc/nov.el/) and even though its maintainer (wasamasa) decided to move the project to his own website, its github page can still be useful. See the discussion about this feature request in its [github page](https://github.com/wasamasa/nov.el/issues/4). Here's a quick summary, it will be too slow unless caching is used, and implementing that is too cumbersome.

**Comment by santiyounger** [comment]
thanks @Charlie-Gordon unfortunately without global search I had to look for an alternative solution. It's a shame nov.el has this limitation. 

I still love love org-noter! So thank you for your great work
