### ISSUE TITLE
Can't run 'org-noter-sync-prev-note' with C-M-p

### ISSUE THREAD

**Issue by kflc** [weirdNox/org-noter#14]
This is what the help command says about my C-M-S-p:

_"C-M-p (translated from C-M-S-p) runs the command org-noter-sync-prev-note"_

So I can run it with C-M-S-p, which gets silently translated to C-M-p, but pressing C-M-p doesn't do anything.

I'm a newbie in Emacs, so I'm not sure of what is causing this, so I don't really know if this is the appropriate place to ask about it.

I'm running Xubuntu and, as far as I could check, my XFCE doesn't have any bindings attached to C-M-p, so I think it's unlikely the keys are getting captured before getting to Emacs.

Thank you!

**Comment by weirdNox** [comment]
Hello there! Does Emacs provide any helpful information when typing `C-M-p` with `describe-key`?

**Comment by kflc** [comment]
When I run `describe-key` and press `C-M-p`, Emacs doesn't even react to the combination and keeps prompting for a key.

I've just tried this: removed my init.el file, ran Emacs and tried it again. Still nothing. So it's clearly not org-noter's fault. I'm sorry I brought the issue here.

I can add a Shift to it though, so it's barely a problem really. Thanks for org-noter, man!

**Comment by weirdNox** [comment]
> I'm sorry I brought the issue here.

Oh, don't worry :) that's great you've figured it out, probably it is your WM capturing the shortcut then.

> I can add a Shift to it though, so it's barely a problem really.

You can also change the keybinding to whatever you want using `define-key`, as a workaround! :)
