### ISSUE TITLE
Highlight

### ISSUE THREAD

**Issue by AtomicNess123** [weirdNox/org-noter#160]
Does org-noter highlight the fragment of text at which a note is made? Thanks.

**Comment by c1-g** [comment]
Org-noter doesn't do the highlighting, it just setup the window layout and takes care of syncing location when you scroll. 

The highlighting is done by another package that's used to view pdf files called [pdf-tools](https://github.com/vedang/pdf-tools) via its `pdf-annot-add-highlight-markup-annotation` command.
