### ISSUE TITLE
org-noter maintenance // fork // future?

### ISSUE THREAD

**Issue by dmitrym0** [weirdNox/org-noter#173]
I drafted a letter (below) to @weirdNox without first checking if I can find his email. I spent a few minutes googling, but don't know how to contact him directly so I'm posting it here in hopes that it reaches him. The goal is to open a conversation to see how we can move the maintenance of this package forward. 

-- 

Hello weirdNox,

I hope this email finds you well. My name is @dmitrym0 and I am writing to express my admiration for the org-noter package that you created. Myself and @petermao have been using it daily and have found it to be an invaluable tool in our work.

We understand that you no longer have an interest in maintaining the package and would like to propose that we take over its maintenance. We have been working on updating the functioanlity, fixing bugs and improving documentation for the past couple of months. Our goal is to ensure that the existing users continue to benefit from this package and that it remains a useful tool for them.

We understand that org-noter is your creation and would like to respect your decision in this matter. However, we believe that with our efforts, the package will continue to be a valuable asset for its users. If necessary, we are willing to fork the package to ensure its continuous development and maintenance.

Here's @petermao's work: https://github.com/petermao/org-noter
and mine: https://github.com/dmitrym0/org-noter-plus-djvu

We intend to converge shortly. 

Thank you for your time and consideration. 

Dmitry

**Comment by petermao** [comment]
Hi Gonçalo (@weirdNox),

I am in agreement with @dmitrym0 on this.  We would prefer to take over maintenance of this package under the same name (vs fork w/ a new name), and would greatly appreciate your blessing and input on the direction we've taken.  This would ensure continuity for the user community.

Our major shortcoming right now is that we are both PDF focused, so other formats are not receiving any attention from us.

Peter
https://github.com/petermao/org-noter

**Comment by c1-g** [comment]
Haha, I burnt out about a year ago. I'm glad you guys are picking up the torch! Are both of your forks considered as separate project? I wanna merge with one of you so I can contribute once again.

**Comment by petermao** [comment]
Hi Charlie-- Dmitry and I are keeping each other's repos as remotes and periodically merge.  We're in frequent email contact and occasionally meet via jitsi.  We both also have your repo as a remote, so if you spin up again, we'll see it.
