### ISSUE TITLE
org-noter--doc-approx-location: Symbol’s function definition is void: assert

### ISSUE THREAD

**Issue by Jean-MichelC** [weirdNox/org-noter#19]
Well, everything is in the title: I have this bug when i call org-noter, which makes it unusable.

I changed somewhere in the code `(assert window)` into `(cl-assert window)` and got it to work.
Not sure why. 
I'm pretty sure there is a better fix, however although I use emacs heavily for org-mode, I no it only superficially because I'm not a coder, so not able to do better.

If this helps: `M-x version` answers `GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.28) of 2018-05-01`

**Comment by weirdNox** [comment]
That's strange! When does that happen? When calling `org-noter` from a PDF or from the notes file?

**Comment by weirdNox** [comment]
If you could, I'm going to ask you two things:

- Is org-noter up to date? Have you installed it recently? If not, please update it and try again, as it could have been fixed recently (even though that assert is relatively recent..)
- Could you try to reproduce it with `emacs -Q`? After running that command, you'll have to load the package manually, by running `M-x eval-expression RET (package-initialize)`.

**Comment by Jean-MichelC** [comment]
Yes of course I volonteer to help if possible.

1. org-notre has been installed yesterday (or the day before).
2. Could you provide more detailed steps after emacs -Q ?

**Comment by weirdNox** [comment]
> org-noter has been installed yesterday (or the day before).
Ok, so it is up to date, thanks

> Could you provide more detailed steps after emacs -Q ?
So, the steps are:

1. Open a terminal and run `emacs -Q`. This will open Emacs without loading any configuration.
2. Run `M-x eval-expression RET (package-initialize) RET`. This will setup the packages autoloads, so even though it is not loaded, you should be able to run `org-noter` by now.
3. Go to an Org file (C-x C-f) and run `org-noter` inside a heading. This should ask you for a PDF file or create the session if that heading already has a document associated.

I think this is what it takes to do it, but if you don't understand something please do say. :)

**Comment by Jean-MichelC** [comment]
Btw, after `emacs -Q` :

`GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.28) of 2018-05-01`
`Org-mode version 8.2.10`

**Comment by weirdNox** [comment]
Ohh, I only read the bug report correctly now! I thought the assert was firing, but the problem is that the assert is missing.

So, after reading the source code, my `assert` is defined as an alias to `cl-assert` inside cl.el, which is described as "Compatibility aliases for the old CL library.". My emacs must have been importing it this whole time, which is why I haven't encountered this bug.

Anyway, I'll just do what you suggested in the bug report and rename it to `cl-assert`. That's the right thing to do :)

**Comment by Jean-MichelC** [comment]
OK perfect !
