### ISSUE TITLE
How would it possible to get the current line of the pdf to make it the title of the note ?

### ISSUE THREAD

**Issue by Jean-MichelC** [weirdNox/org-noter#21]
Hi,

everything is in the title of this subject.
I'd like, being in a pdf in `org-noter-doc-mode`, at a certain point, pressing `i` and getting a proposed value for the title of the note, that would be the whole current line.

This would be a very convenient way to rebuild in the `org-noter-notes` document the outline of the pdf document (especially for pdf without outlines), by just taking notes through `i` on each headline of the pdf document ...

In every other software, the question would be:

> Is this possible ?

But this is emacs, so the question is:
> How is that possible ?

;-)

**Comment by weirdNox** [comment]
Yes, I think this is not too hard to do... I'll investigate :)

Anyway, for PDFs that do have an outline, you can use `org-noter-create-skeleton`!

**Comment by Jean-MichelC** [comment]
Hey weirdNox, I see that you closed my issue : does this mean there is no hope for me ?

I have seen the `org-noter-create-skeleton` function, which is great, by my suggestion would be for documents which have no outline : indeed, to help to reconstruct the outline...

Any perspectives ? ;-)

**Comment by Jean-MichelC** [comment]
Stupid me ;-) If only I clicked on the link to the change 1ae460c ...
==> Perfect, it helps a lot.
Now, a further enhancement would be as I decribed in the still open issue 22

**Comment by weirdNox** [comment]
> I see that you closed my issue
