### ISSUE TITLE
Extract highlighted text and annotation text

### ISSUE THREAD

**Issue by et2010** [weirdNox/org-noter#22]
Thanks for making this fantastic package! `org-noter-create-skeleton` works great for annotations. I'm wondering whether the highlighted text and annotation text could be extracted as subtree content?

**Comment by weirdNox** [comment]
I'll investigate when I have the time, but certainly seems possible! Thanks :)

**Comment by et2010** [comment]
I've implemented this feature on my fork. I'm not skilled at elisp, so it will probably have bugs.

https://github.com/et2010/org-noter/commit/c0711a61bb0307eff63e36b5cd8d0a44b790350e

https://github.com/et2010/org-noter/commit/a7a40f2d7ff49a66f79080532feb266158c7828e

https://github.com/et2010/org-noter/commit/570336beab94f03b05ff321d9e69206ec4ed879a

**Comment by Jean-MichelC** [comment]
I'd love it too.

In my work-flow, I regularly face the following issue : having a pdf with no outline, and needing the outline. So in need to reconstruct it. 

A good way would be to highlight the titles/subtitles, and then get them automatically transfered in org-mode through org-noter-create-skeleton ...

**Comment by et2010** [comment]
> In my work-flow, I regularly face the following issue : having a pdf with no outline, and needing the outline. So in need to reconstruct it.

I usually build outline/bookmarks by PDFXchange editor. It has a feature to build outline from selected text style automatically which I find very handy. After that you can extract the outline by org-noter/pdf-tools.

**Comment by weirdNox** [comment]
@et2010, thanks for the references, they were very helpful!
