### ISSUE TITLE
The extracted outlines are not in correct order when the document has two columns

### ISSUE THREAD

**Issue by et2010** [weirdNox/org-noter#23]
The extracted outlines are not in correct order when the document has two columns. For example,

Expected:

```
1.
2.
  2.1
  2.2
  2.3
3.
...
```

Actual:

```
1.
  2.1
2.
  2.2
  2.3
3.
...
```

The outlines are made by PDFXchange Editor

**Comment by weirdNox** [comment]
Hello there! Thanks for the report! I'm a bit busy with college right now, so, if you don't mind using your fork for now, I'll review these when I have more time.
