### ISSUE TITLE
Handle notes that are not in the same directory as the PDF

### ISSUE THREAD

**Issue by et2010** [weirdNox/org-noter#24]
Here is my use case:

First I insert a heading in my note file, then I run `org-noter` and input the location of the PDF document. I can open PDF from my notes with this workflow. However, if I then open the same PDF and run org-noter, the note file is not set and org-noter will prompt to create one.  How could I make org-noter to know there is already an associative note file? I'm asking since all my PDFs are in a Zotero storage and I would like to collect my notes in a note file outside the Zotero storage folder. Is that possible?

**Comment by weirdNox** [comment]
Yes, this is a planned feature, where you have the notes file on a user defined location (like Documents or whatever) and it finds the file there. 

Also wanted to say that I'm very sorry, but I probably won't be able to add new features to org-noter until ~end of june... I've got finals and time is critical right now!

**Comment by et2010** [comment]
Thanks! I really appreciate your work. My workaround is to use some python scripts to modify the PDF document so that the notes file path is added to the metadata. After a few modification, I'm now able to open PDF and run org-noter to get to my notes file. Here is my working branch: 

https://github.com/et2010/org-noter/tree/work

It's not clean but it works. Cheers!

**Comment by weirdNox** [comment]
If everything is working ok, this is now a feature of org-noter! You can set a custom search path and have it mixed with parent folders and whatnot :D

(Today is the first day I start working on `org-noter` again and this feature was medium sized, so there may be bugs! Ahah)
