### ISSUE TITLE
How would it possible to get the current line of the pdf to make it the title of a /precise/ note ?

### ISSUE THREAD

**Issue by Jean-MichelC** [weirdNox/org-noter#25]
Hi,
This is the continuation of issue 21 which is solved.

I tried the new possibility offered by the default-title when pressing `i`, which is great. `i`, bound to `org-noter-insert-note`, now allows to capture a text, in my use-case a title, from the document buffer into the notes buffer.
However there is a limitation, which can a significant drawback in some cases : when you want to capture /several/ titles from the /same page/ of the document buffer, it does not work. After the first capture of a title by `i`, selecting a second title, on the same page, and pressing `i` doesn't result in a second note but just position the point in the notes document under the heading of the previously created headline.
So the need is now to be able to have the default-title mechanism available in `M-i` (`org-noter-insert-precise-note`).
The ideal sequence would be:
- selecting the title
- pressing M-i
- getting the default-title
- skipping the mention "click where you want the start of the note to be" : obviously the start of the note should be at the start of the selected region.

Hoping this is clear !

**Comment by weirdNox** [comment]
Hi there, I'll add this to the todo list! BTW, if you want to create multiple notes on the same page *without* precise notes, you could just `C-u i` which forces a new note :)

Btw, I'm very sorry, but I probably won't be able to add new features to org-noter until ~end of june... I've got finals and time is critical right now!

**Comment by Jean-MichelC** [comment]
Well it will wait until july then, no problem for me and your finals are much more important. (Mine were yeeeeaaaaars ago ...).

**Comment by weirdNox** [comment]
Hello! Could you try the implementation of the feature you suggested? I think it does what you want :)

By the way, with a selection, you can now append the selection contents to the body of a note! Just select something and press `i`!

Also, as I said before, you can force the creation of a new **non-precise** note with `C-u i`, even if you already have a note on that page.
