### ISSUE TITLE
M-x org-noter failed on epub file opened with nov.el 

### ISSUE THREAD

**Issue by hekinami** [weirdNox/org-noter#26]
M-x org-noter failed with 'Wrong type argument: stringp, nil' message. 

```
   ((memq major-mode '(doc-view-mode pdf-view-mode nov-mode))
    (if (org-noter--valid-session org-noter--session)
        (progn (org-noter--setup-windows org-noter--session)
               (select-frame-set-input-focus (org-noter--session-frame org-noter--session)))

      (let* ((document-name buffer-file-name)
             (document-non-directory (file-name-nondirectory document-name)) ; <- this line
             (document-directory (file-name-directory document-name))
             (document-base (file-name-base document-name))
             (document-location (org-noter--doc-approx-location 'infer))
             (search-names (append org-noter-default-notes-file-names (list (concat document-base ".org"))))
```

And by debug, we can see the  line pointed out is the root cause. Seemingly there is no buffer-file-name for nov.el buffer.

**Comment by weirdNox** [comment]
Hello there! I don't know if you read the other issues, but at the moment I'm a little busy, so I'm not pushing out any features or bugfixes... I'll try to look at this as soon as I can!

Thanks!

**Comment by weirdNox** [comment]
Hello! Finally had some time to look at this :) 

I think this may be a problem with nov.el itself, because it is deleting `buffer-file-name`. It is doing that in order to 

> disable autosaves and save questions

but there should be better ways to do that. I'll create an issue there and report back!
