### ISSUE TITLE
Add a non-global way to open annotator in the same frame

### ISSUE THREAD

**Issue by memeplex** [weirdNox/org-noter#28]
This is trivial to achieve as customization by just defining a function that first unsets org-noter-always-create-frame and then calls org-noter. But I believe it must be provided out of the box because the current mode of defaulting to a new frame is far from a good guess that just works in the majority of use cases. Unfortunately numerical arguments are already taken for the org-noter function, so maybe an org-noter-here wrapper?

**Comment by memeplex** [comment]
I mean something like:

```elisp
(defun org-noter-here (&optional arg)
  (interactive "P")
  (let ((org-noter-always-create-frame nil))
    (org-noter arg)))
```

**Comment by weirdNox** [comment]
I never use that feature so I don't really have a preference about it. The function you suggested is fine for me :) If you prefer, we could also reserve the prefix argument 0 to do that!

**Comment by memeplex** [comment]
If 0 is free I'm all for it!

**Comment by weirdNox** [comment]
It's currently being used, but well, we could change it... ahah.

Ok, so the new prefix argument functionality will be:
- Greater than 0: View PDF only
- Equal to 0: Create session on frame
- Less than 0: View PDF directory

**Comment by memeplex** [comment]
Kewl, thanks!

**Comment by weirdNox** [comment]
That's it, thanks for the suggestion!
