### ISSUE TITLE
org-noter-create-skeleton is now broken

### ISSUE THREAD

**Issue by analyticd** [weirdNox/org-noter#29]
I tested this on several books. It used to work. Perhaps there has been a change to pdf-tools on which it relies? pdf-info-outline or (although I am able to get salient info from calling (pdf-info-outline) directly? If I pretty print output-data it seems to have the data needed, but I think fails when it goes to access things while inserting. Used to work fine for most PDF books. Great package otherwise. Thank you.

Example output-data

` ["Contents"
  (4 . 0.137085)
  2]
 ["About the author"
  (9 . 0.137085)
  2]
 ["Note about this eBook edition"
  (10 . 0.137085)
  2]
 ["Preface"
  (12 . 0.137085)
  2]
`
etc

**Comment by weirdNox** [comment]
Oops, my bad! I only updated the Annotations part, forgot about the Outlines...

Should be fixed, please update and test it, if not, reopen this issue again :)

**Comment by analyticd** [comment]
It is fixed. Thanks Gonçalo Santos! And thanks for the nice package. It
is very helpful.
