### ISSUE TITLE
`org-noter-create-skeleton` does not include content of highlights

### ISSUE THREAD

**Issue by brabalan** [weirdNox/org-noter#30]
In pdf-tools, it is possible to highlight some text then to add some comments (by clicking on the highlight). Unfortunately these comments are not exported when doing an `org-noter-create-skeleton`.

**Comment by weirdNox** [comment]
Yes, this would be possible!

Currently we ask if the selection should be inserted. Should we have the combinations of inserting both, none and only one of them?

**Comment by brabalan** [comment]
That may be too many options (especially if one starts wanting to do different things for different annotations: one can add comments to strikethrough, squiggly, and so on).

I suggest the following: it's either all or nothing, and to distinguish between the highlight and the comment, it could be extracted on two lines like this:
```
"highlight with quotes"
comment
```

**Comment by weirdNox** [comment]
Another option could be to create subheadings called `Highlighted content` and `Comments`, when they exist. Maybe it's better, because each one it may span multiple lines, no?

**Comment by brabalan** [comment]
Yes, this  is true. It would be a nice solution.

**Comment by weirdNox** [comment]
Ok! I'll try to do it next week :)

**Comment by weirdNox** [comment]
Just noticed that it was a bug on the code, because it was already extracting both the comments and the highlight contents :P
