### ISSUE TITLE
Feature request: extract both outline and notes with `org-noter-create-skeleton`

### ISSUE THREAD

**Issue by brabalan** [weirdNox/org-noter#32]
Could it be possible to have the option to extract both the outline and the annotations (put in the right place in the outline) using `org-noter-create-skeleton`?

**Comment by weirdNox** [comment]
This may contain bugs, so test it and check if it does what you want. The annotations will be created inside the previous outline item (hopefully! :P)

**Comment by brabalan** [comment]
This is perfect, thanks a lot!
