### ISSUE TITLE
Multiple frame support

### ISSUE THREAD

**Issue by HaoZeke** [weirdNox/org-noter#34]
I was wondering if there is a mechanism for working with the document open in another frame...

I usually work on a two monitor setup so having notes and the document in one split frame is kind of sub optimal.

**Comment by weirdNox** [comment]
Yes there is! Check out `org-noter-notes-window-location` :) 

You can set it globally in your config and you may override it in each document (permanently or just for the current session) with the command `org-noter-set-notes-window-location`.

**Comment by weirdNox** [comment]
I closed this assuming I answered your question, but if you wanted something different, feel free to reopen!

Also, if you don't know it already the docstrings of the commands explain extra functionality that you may like and use in your workflow :)

**Comment by HaoZeke** [comment]
Thanks for the heads up about the docstrings, I'm still working my wway around emacs, mostly made the switch to use `org-noter` for college :D
