### ISSUE TITLE
poor variable name: org-noter-set-doc-split-percentage

### ISSUE THREAD

**Issue by jack99999** [weirdNox/org-noter#35]
rather pedantic...

the default value for org-noter-set-doc-split-percentage is 0.5. i suspect that it's not really a percentage at all... it's a fraction.

**Comment by weirdNox** [comment]
Thanks for the heads-up! When I created it something sounded wrong, but I just moved on :P

I'll make this variable obsolete and change it to fraction :)

**Comment by weirdNox** [comment]
Please test it as I didn't have time to do so :)

**Comment by jack99999** [comment]
sorry, been away... is working fine for me. thanks.

**Comment by weirdNox** [comment]
Ok, great!

By the way, if you want to insert a ?, you need to use `C-q ?`, because ? alone is the binding for the help of the `completing-read`.
