### ISSUE TITLE
Cant type spaces in notes.

### ISSUE THREAD

**Issue by fxkrait** [weirdNox/org-noter#36]
This might be something related to my emacs configuration. 
Whatever setting I have incorrectly configured, should be explicitly stated in the directions.
Thanks for help in advance.

I can write anything in a note, but when I try to do a space (or tabs), I cannot. 
It says:
[No match]
or 
[Sole Completion]

It seems to be searching for the note to already exist, but I'm trying to define it.

.emacs: https://pastebin.com/pA2kpRTk

**Comment by fxkrait** [comment]
I have an org file, hit i to add a new note. By note are you referring to the below? "NOTE"?
  
** NOTE
   :PROPERTIES:
   :NOTER_PAGE: 13
   :END:

Yes, the tab completion is for those "NOTE" titles.
I can not make the title have a space in it.

**Comment by weirdNox** [comment]
I believe this solves your problem, give it a try :) I hadn't noticed because I use Ivy which works differently! :P
