### ISSUE TITLE
One org mode file for each document?

### ISSUE THREAD

**Issue by tdehaeze** [weirdNox/org-noter#39]
Hi,
I switched from Interleave to org-noter few weeks back and I am wondering if I can have one orgmode file for each document.
From the documentation it seems not:
> This package only works like the multi-pdf mode of Interleave - you can’t open a session without having a parent headline.

But it would be great be able to define one noter_document for one orgmode file using the following:
`#+NOTER_DOCUMENT: ./pdfs/document.pdf`

Then for me it is easier to export my notes to LaTeX.
Do you think that is possible?
Thank you

**Comment by tdehaeze** [comment]
My workaround right now is having one main Headline in the file dedicated to one particular document.
Then I add `:ignore:` tag to the headline so that it is not exported.

```orgmode
#+TITLE: Sensor fusion for active vibration isolation in precision equipment

* TOREAD Sensor fusion for active vibration isolation in precision equipment :ignore:
  :PROPERTIES:
  :CUSTOM_ID: tjepkema12_sensor_fusion_activ_vibrat_isolat_precis_equip
  :AUTHOR:    Tjepkema, D., Dijk, J. v., & Soemers, H.
  :TYPE:      article
  :JOURNAL:   Journal of Sound and Vibration
  :YEAR:      2012
  :VOLUME:    331
  :PAGES:     735–749
  :DOI:       10.1016/j.jsv.2011.09.022
  :URL:       https://doi.org/10.1016/j.jsv.2011.09.022
  :NOTER_DOCUMENT: ../pdfs/Articles/Sensors/2012 - Sensor fusion for active vibration isolation in precision equipment.pdf
  :END:
```

**Comment by weirdNox** [comment]
Hello there!
Introducing the change you want would involve a bit of work, because the entire code base assumes a root heading. 
Are you not able to achieve the behaviour you want by setting the export scope to Subtree in the export dispatch (the key is `C-s`)? It will use the heading text as title of the exported document, and everything inside it behave like they are level 1 headings.

**Comment by tdehaeze** [comment]
Hello, thanks for the answer.
Very nice solution. I was looking for something like this.
However, the only drawback for me is that it seems I cannot add specific `LATEX_HEADER` commands for each document (lvl 1 headlines). I use them a lot to set latex variables.
Do you know if I can do that?

**Comment by weirdNox** [comment]
Ok, great! :D

Btw, I'm afraid I didn't understand the drawback. I tried to define things with `\newcommand` and then use it inside the notes and it worked, so maybe you are referring to other things?
