### ISSUE TITLE
Does it have to be PDF?

### ISSUE THREAD

**Issue by bdillahu** [weirdNox/org-noter#4]
I'm assuming so, but being able to annotate Word, or even other org-mode documents would be slick... just an idea (or maybe I'm missing it)

**Comment by weirdNox** [comment]
Hello there! `org-noter` supports DocView and, in [the manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Document-View.html), it says 

> DocView mode is a major mode for viewing DVI, PostScript (PS), PDF, OpenDocument, and Microsoft Office documents.

I have not tested it with Word, but I have opened a .xls before and it works. DocView is not great in general, but give it a try and see if it is enough for what you want!

As for general text documents like Org-mode, I have thought about it before. However, I don't really know how it would work, because, usually, these documents are more volatile. How would it know where a specific note is attached if the text file changes? Ideas are welcome!

**Comment by yubrshen** [comment]
Supporting annotation to the web page would be great.

**Comment by weirdNox** [comment]
@yubrshen While the idea is great, I don't think it is a feasible thing to do... 

It would have to have some connection to a external browser (or a browser inside Emacs) and, even then, it would be hard to have reference points for notes (there are no pages like in a PDF) and it would be hard to maintain notes tied to specific things (the underlying page could change without you even knowing).

As such, I don't think `org-noter` is the ideal tool for annotating web pages. 

If you are talking about taking notes in general, without the benefits of `org-noter` (like synchronization when scrolling and things like that), I think putting a link in a heading and the respective notes inside would be a good alternative.

**Comment by bdillahu** [comment]
I think the web thing would be great, but would love even annotations for a text file. Could work off org-mode headlines for keys, or even something that it inserts maybe?

My thought is that when writing a long document/book/whatever, having "out of band" notes and comments would be great.

**Comment by alraban** [comment]
Support for electronic book formats (like epub or mobi) would be particularly nice; my electronic documents are about half-pdf, half-epub.  There are a few epub reader modes for emacs (ereader.el and nov.el come to mind) that could be used as the "other pane"

**Comment by weirdNox** [comment]
I also think supporting nov.el would be great, however we stop having pages, which are the reference for storing notes... Any ideas? Using each document/chapter as the only point of reference seems too vague.

**Comment by alraban** [comment]
Well, that's one of the primary drawbacks of nov.el.  For example, ereader.el loads the entire file at once, so you could potentially just use global line-numbers with it.  Nov.el would obviously be preferable as it renders more nicely (and is under active development) but it lazy-loads one chapter at a time, which makes both annotation and searching much harder. 

If it were me, I would note the chapter that the annotation is in, and then include the text surrounding the annotation.  You could then "find" the annotation using a two part process, opening nov.el to the appropriate chapter and then searching (isearch or something else) within the newly opened chapter.
 
A more complex solution: I don't know a lot about the internal file structure of epubs, but some e-readers seem to divide epubs up into uniform units that don't change based on font size or re-flowing.  For example, if you open an e-book in calibre's reader the book might show 1300 "units" in the progress tracker. Depending on your font-size turning the page might advance one unit or two or three.    But the number of units is consistent and uniform for a given e-book, so it's obviously either intrinsic to the file or mathematically derived by calibre.  My guess is that it's based on word count as a calibre "unit" usually translates to about .5 of a printed page.

So I'd suggest either using an ereader mode that loads the whole file (like ereader.el), or you could do a two part loading process, or you could perform some kind of static analysis on the relevant epub to create more granular divisions, and then store the results of the analysis in the annotation file.

**Comment by weirdNox** [comment]
I made a dedicated issue for nov.el support in #6, check it out!

**Comment by alraban** [comment]
Awesome!  Glad you've got a lead.

**Comment by yubrshen** [comment]
I think the following ideas are very much worthy to explore.

**Comment by weirdNox** [comment]
Initial support for Nov.el (EPUB) has been added in a197ae7, needs lots of testing because it was a major refactor!!

**Comment by weirdNox** [comment]
I'll close this issue for now, as it is a bit generic and `org-noter` now supports PDF, EPUB, Microsoft Office, DVI, PS, and OpenDocument (didn't test anything besides PDF or EPUB, but no bugs have been reported either!)

Even though I think the current document support should be enough for most purposes, if there are more suggestions for specific document types or handlers, open a new issue please!
