### ISSUE TITLE
Trouble with `org-noter-hide-other`

### ISSUE THREAD

**Issue by HaoZeke** [weirdNox/org-noter#40]
I am a bit confused by the `org-noter-hide-other` property. As defined from the source:

```emacs-lisp
(defcustom org-noter-hide-other nil
  "When non-nil, hide all headings not related to the command
  used, like notes from different locations when scrolling."
  :group 'org-noter
:type 'boolean)
```

The above segment seems to mean that other notes will be displayed in the `org` buffer. However, when I have multiple documents synced to a single file, setting `org-noter-hide-other` still narrows the view down to each document's heading.

![Full Notes File](https://user-images.githubusercontent.com/4336207/44984148-5d00f100-af99-11e8-8d78-63e8499931b4.png)

![View after running `org-noter`](https://user-images.githubusercontent.com/4336207/44984189-7bff8300-af99-11e8-9878-d35090c2ba4c.png)

In essence I would prefer no window to pop up with the subtree only view and just edit the full notes file.

**Comment by weirdNox** [comment]
Hey! I'm not sure I understood your question, but that variable controls whether other notes are hidden when you scroll to a page with something else. 

For example, being `org-noter-hide-other` non-nil and having notes on pages 2, 3 and 4, when you go to page 4, both notes from pages 2 and 3 are collapsed. When it is `nil`, the notes would stay like they were before, open or collapsed.

**Comment by HaoZeke** [comment]
Oh now I understand it's usage. Actually I was wondering if there was a way to start and `org-noter-session` without hiding the other `*` level headings which are also linked by `org-noter` to different documents.

More specifically, I have a file, say `languages.org` with the following:

```org
* English
I have a bunch of books

** Wren and Martin
:PROPERTIES:
:NOTER_DOCUMENT: ../Wren.pdf
:END:

*** A note
:PROPERTIES:
:NOTER_PAGE: 27
:END:
I live here

** Schaums English
:PROPERTIES:
:NOTER_DOCUMENT: ../sch.pdf
:END:

*** Wild note
:PROPERTIES:
:NOTER_PAGE: 27
:END:
A wild note has appeared!

* Spanish
I also have books here.
```

The issue is that when I run `org-noter` from say, `Schaums English`, a new split opens and I cannot see the content of `A note` or even `Wren and Martin` or `English`. All I can see is `Wild note`.

I was wondering if there is a way around this. Namely I would like to be able to use [helm-org-rifle](https://github.com/alphapapa/helm-org-rifle) to switch to notes under other `org-trees` without closing the current `org-noter` session.

**Comment by weirdNox** [comment]
At the moment, there is no way to do that automatically, and not doing that narrowing could cause some unpredictable behavior. However, in today's update I added an "ID" to each session by using text properties, so org-noter can find the correct root heading even if that document is annotated multiple times.

For now, try to run `M-x widen` and see if everything works ok. Please report back, so I know if it is worth implementing that as a feature.

**Comment by HaoZeke** [comment]
So, `M-x widen` works well, however it does sometimes unpredictably open a new copy of the `pdf` instead of going to the note in the existing pdf.

**Comment by weirdNox** [comment]
> However it does sometimes unpredictably open a new copy of the pdf instead of going to the note in the existing pdf.

Have you updated org-noter today? If it is up to date, then could you please send me the Org file that reproduces the bug?

> I just realized that it might be better to simply switch to the .org file buffer to search, however I can't get back to the org-noter narrowed down session again.

That's what I usually do :P The org-noter buffers are named "Notes of ...". In either case, you can select the document and run `M-.`, which is the binding for the command `org-noter-sync-current-page-or-chapter`.

**Comment by HaoZeke** [comment]
Sorry I haven't been able to keep up with this issue.. I've mostly just changed my work flow, but when required, `M-x widen` is working well too.. Thanks!

**Comment by weirdNox** [comment]
No problem :)

**Comment by ramanddopor-alt** [comment]
org-noter-hide-other
