### ISSUE TITLE
Helm and creating new notes problem

### ISSUE THREAD

**Issue by Chobbes** [weirdNox/org-noter#41]
Hey there!

So, this is definitely more of an issue with helm than org-noter, but I wanted to raise the issue because this has been causing me an endless amount of grief.

Normally when you insert a new note in org-noter you get a prompt asking you to title the note... If you just hit enter you should get "Notes for page $p$" inserted. HOWEVER, if you use helm, the call to completing-read to do this is replaced by helm. Normally this is fine, but in the case of org-noter it's pretty irritating! Pressing enter causes nothing to happen. No note / header is inserted, and the prompt for the note title disappears...

Apparently in helm you have to hit C-<ret> or M-<ret> to get the default completing-read behaviour for hitting <ret>:

https://github.com/emacs-helm/helm/issues/700

Might be a good idea to make a note of this somewhere to save poor sad souls like myself. Perhaps it might even be a good idea to let us customize the completing-read function used by org-noter-insert-note?

**Comment by Chobbes** [comment]
Alternatively, I would love to have a command that never prompts for a title for the note, and just inserts using the default title with the page number. It would save a few keypresses every time I wanted to make notes!

**Comment by weirdNox** [comment]
I'll see what I can do :)

**Comment by weirdNox** [comment]
Check out the new variable `org-noter-insert-note-no-questions` and the function `org-noter-insert-note-toggle-no-questions` (bound to `C-i` by default). :)
