### ISSUE TITLE
error: Before first headline at position 1 in buffer "$FILENAME"

### ISSUE THREAD

**Issue by emacsomancer** [weirdNox/org-noter#43]
Trying to run `org-noter` on some older notes I made (with org-noter) I get the error  ` Before first headline at position 1 in buffer "$FILENAME"`, and it does not open the file(s) [though both the pdf and the notes files exist].

**Comment by weirdNox** [comment]
Could you post a minimal reproduction case? I got that error this week but pushed a fix, maybe it was the same error.

**Comment by emacsomancer** [comment]
Since I'm not sure what triggered it, it's not clear how to reproduce it. I'll wait and if the pushed fix resolves it.

**Comment by weirdNox** [comment]
Ok! The bug I fixed had something to do with headings without contents inside notes, so check if your old document had that. If not, I don't know what caused it ahha

If it happens again, also try to repeat the bug with `toggle-debug-on-error` in order to get a backtrace :)

**Comment by emacsomancer** [comment]
User error, it turns out. I had added local variable to the top of the file and this is what triggered this error. Adding a "local variable" org heading at the end of file works without issue.
