### ISSUE TITLE
Separate frames for pdf and notes buffer

### ISSUE THREAD

**Issue by abradd** [weirdNox/org-noter#51]
Is it possible to have separate frames for the pdf and notes buffer?

I prefer to have my pdf and notes buffer on two separate screens primarily to improve readability of the pdf without the need for zooming and panning.

**Comment by yanghaoxie** [comment]
Yes, you can. Check `org-noter-set-notes-window-location` and `org-noter-set-notes-window-behavior`.

**Comment by abradd** [comment]
Ahh that is fantastic. Thanks!

**Comment by weirdNox** [comment]
Oh, great! I'm very short on time at the moment, so it being already implemented is fantastic! :tada: Thanks @yanghaoxie!

@abradd, you probably have seen it already but you can customize the global setting and a document-specific setting if you want to override it :)
