### ISSUE TITLE
not availible in melpa (emacs --version GNU Emacs 27.0.50)

### ISSUE THREAD

**Issue by Xparx** [weirdNox/org-noter#52]
I'm wondering if this is a problem on my end or a version of emacs problem.

I've been running interleave-mode and got a new computer and setup emacs. 
I tried to install interleave but could not find it in my melpa repo `M-x package-install int<TAB><TAB>`. 
Proceeded to look in to interleave and found this repo which seems newer and fresher. But I get the same result, that it's not available in melp for me.

I'm wondering if this is because of my emacs version or if i should be able to install it but there is an issue on my end.

**Comment by weirdNox** [comment]
Great! Hope you like it :)
