### ISSUE TITLE
Session parsing

### ISSUE THREAD

**Issue by raketeneis** [weirdNox/org-noter#53]
I had some issues with `org-noter--parse-root`. On session creation, `info` seems to contain two elements, namly the note buffer name and the property value that tells org-noter where the document for the note is. So, on session creation these elements are correctly assigned here:

```elisp
(let ((notes-buffer (aref info 0))
      (wanted-prop  (aref info 1)))
        (unless (and (buffer-live-p notes-buffer) (stringp wanted-prop)
                     (eq (buffer-local-value 'major-mode notes-buffer) 'org-mode))
          (error "Error parsing root with invalid arguments"))
```

Later, however (for instance when I attempt to kill the session), `info` contains a whole lot more, and the elements at positions 0 and 1 are no longer what is expected in the above snippet, so the error is triggered.

I did a quick workaround by modifying the condition of this clause to 
```elisp
(and (vectorp info) (<= (length info) 2))
```
so the other clause will be evaluated after `info` has grown.

This seems to solve all problems I had so far, but I'm not really sure what else is happening in `org-noter--parse-root`, so maybe there is a more well-thought out fix.

Thanks for the great package!

**Comment by weirdNox** [comment]
Hi there! Thanks for the report!

I don't think I am able to reproduce this bug. I use this package daily with my college notes, so I'm out of ideas for reproduction cases :P Could you provide one which triggers the error?

**Comment by weirdNox** [comment]
Oh! Maybe I know what the problem is... What version of Emacs are you using, in which operating system? I believe it may have to do with the fact that `cl-structs` may be made with vectors in the version you are using..

From [this manual page](https://www.gnu.org/software/emacs/manual/html_node/cl/Structures.html),
> The argument should be one of the symbols vector or list. This tells which underlying Lisp data type should be used to implement the new structure type. Records are used by default, but (:type vector) will cause structure objects to be stored as vectors and (:type list) lists instead.
> The record and vector representations for structure objects have the advantage that all structure slots can be accessed quickly, although creating them are a bit slower in Emacs Lisp. Lists are easier to create, but take a relatively long time accessing the later slots. 

It says that records are used by default, but maybe in your Emacs, vectors are used? I don't know, but I think that's it.

And it explains why you are seeing it "growing", `info` may be a vector with two elements OR a structure which has a lot of other information.

**Comment by weirdNox** [comment]
After searching on Google, I'm even more sure that's the case, as I found [this article](https://nullprogram.com/blog/2018/02/14/):
> In Emacs 26, cl-defstruct uses records instead of vectors.

So you are probably using Emacs 25 which uses vectors and triggers the first case incorrectly!

**Comment by raketeneis** [comment]
You're right, that must be it! I'm indeed using Emacs 25.1.1 on macOS.

**Comment by weirdNox** [comment]
Ok, I've pushed a fix, when it gets to MELPA please test it and say if it works :)

**Comment by raketeneis** [comment]
Yes, works like a charm now. Thanks!
