### ISSUE TITLE
When I launch org-noter from a PDF Tools pdf document

### ISSUE THREAD

**Issue by stardiviner** [weirdNox/org-noter#59]
# Reproduce steps

1. open PDF document file with PDF Tools
2. when is in PDF Tools buffer, I execute command `org-noter`.
3. org-noter launch a new seesion frame. But when I press `[i]` in new session frame's PDF window, it reports error not defined. The original PDF document window in original frame still remains, but I can press `[i]` in original PDF window.

I think org-noter should fix this problem.

**Comment by weirdNox** [comment]
Is that error reported in the created frame or the original one? When I tried to reproduce this, pressing `i` in the new one opened the note insertion query. That error was only triggered when I tried it in the original frame, as expected.

**Comment by stardiviner** [comment]
That error occur in new opened org-noter frame.

**Comment by weirdNox** [comment]
>  In the original frame works.

I'm not sure I'm understanding, when you press `i` in the original frame, it asks you to insert a new note? That should not happen as the minor mode is only enabled on the buffers of the new frame.

Also, I was not able to reproduce the problem :/

**Comment by stardiviner** [comment]
I tested with minimal config, indeed works fine. So then I bisect my init files. I found packaged `org-pdfview` caused this issue. But I checked its source code, have not found related code. Can you review its code?

**Comment by stardiviner** [comment]
I finally figured out why, the pdf-tools hook by using `bookmark.el` to remember PDF file location caused this issue. I removed that config now. Sorry for wasted your time. Bisecting my init config cost me about 40 minutes .....

**Comment by weirdNox** [comment]
No problem! Btw, if you need that functionality with org-noter, you can use `org-noter-set-start-location` :)

**Comment by stardiviner** [comment]
This works very interesting implementation and great, thanks @weirdNox .
