### ISSUE TITLE
Nov.el support

### ISSUE THREAD

**Issue by weirdNox** [weirdNox/org-noter#6]
I just skim read some parts of nov.el and I think it may be possible to support it. 

- The first identification part is `nov-documents-index`
- The other part is the point itself

Nov.el has support for resuming sessions where you left, and uses this scheme for saving the last visited location, so we know this forms unique identification. 

We would need to have a hook in `window-scroll-functions` to see when certain parts of the document become visible. Also, I think the best way to know when the document itself changes is by advising `nov-render-document`. With these two things, I think I can make it work.

Unfortunately, I don't have any kind of deadline for this, or even if I will be able to do this at all. I made org-noter very dependent on isolated pages and this may need another major refactor... We'll see :)

**Comment by usharf** [comment]
Did you look at `ereader`? There's some support for annotation there, which i'm curious about, but didn't try using yet.

```
"Load annotations from the associated Orgmode file.
An annotation is simply an org-link to a position in the ebook,
followed by some text.  The text following the annotation can be
displayed in the right margin.

This function is called interactively instead of automatically
because it is slow.

See `ereader-annotation-files', `ereader-hide-annotation',
`ereader-show-annotation', `ereader-hide-all-annotations', and
`ereader-show-all-annotations'."
```

**Comment by weirdNox** [comment]
I looked at ereader, but it seemed to already have the annotation feature, so I thought it would be a bit redundant, no?

**Comment by weirdNox** [comment]
Initial support has been added in a197ae7, needs lots of testing because it was a major refactor!!

**Comment by weirdNox** [comment]
Closing this as no major bugs have been reported (_yet!_)

**Comment by usharf** [comment]
Sorry didn’t get a chance to test yet. Will report if there’s anything interesting.

**Comment by weirdNox** [comment]
@usharf No problem! Thanks :)

**Comment by respatialized** [comment]
I'm having issues with this; calling `org-noter` in a headline and specifying an epub as the target opens a new window but causes emacs to freeze completely. It doesn't even get to the stage of logging anything in the messages buffer before I have to kill it.

Trying a clean install with `emacs -q` and `package-install-file` gets past the point of crashing, but even though both nov.el and org-noter have been installed, the only message returned when I try to call `org-noter` with an epub as the target is:

`org-noter--create-session: This document handler is not supported :/`

Any suggestions on how to debug further? Happy to help.

**Comment by weirdNox** [comment]
Do you have the latest version of org-noter and are you able to view the EPUB by opening it using `find-file`, with Nov.el? Don't forget that in order to use Nov.el, you need the following in your init file:
```elisp
(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
```

If yes, then run M-x `toggle-debug-on-quit` and try to press C-g when it hangs. Hopefully this will get you a backtrace of where it was, that may be helpful to debug the situation :)

**Comment by respatialized** [comment]
Thanks for the tip, that got me at least to a backtrace! 

Before it hits the debugger (from C-g), I also saw this in the messages buffer:

```
Error during redisplay: (eval (org-noter--mode-line-text)) signaled (wrong-type-argument number-or-marker-p nil) [432 times]
```

As for the actual debugger, here's the message it displayed:
```
Debugger entered--Lisp error: (quit)
  redisplay_internal\ \(C\ function\)()
```

Hope this helps! I'll try to reproduce in a setup with fewer customizations.

**Comment by GregorZattler** [comment]
Hello and thanks for org-noter.  My first attempt is to annotate an epub.  But I cannot add more than one note. 

I installed emacs26.1.1 from source, created a minimal .emacs, installed nov and org-noter, customized them as explained in the README and in this issue. 
Then I start emacs, open the epub, open the notes file, point being at the first heading I press "C-c n", then I get an error, but a new frame is opened and point is in the epub.  I press "i" now and get another error.  This is my *Messages* at this point:


org-noter--parse-root: Error parsing root with invalid arguments
Error running timer ‘org-noter--doc-location-change-handler’: (wrong-type-argument number-or-marker-p (8 . 2571))
Wrong type argument: number-or-marker-p, (8 . 2571)
Error running timer ‘org-noter--doc-location-change-handler’: (wrong-type-argument number-or-marker-p (8 . 2571))



and this is .emacs (epub file name scratched for privacy):

(require 'package)
(add-to-list 'package-archives (cons "melpa" "http://melpa.org/packages/") t)

(package-initialize)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(inhibit-startup-screen t)
 '(package-selected-packages '(org-noter nov dh-elpa notmuch dired-subtree))
 '(tool-bar-mode nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "DejaVu Sans" :foundry "unknown" :slant normal :weight normal :height 172 :width normal)))))



(require 'org-noter)
(require 'nov)

(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))

(define-key org-noter-doc-mode-map "\C-i" nil)
(define-key org-mode-map "\C-cn" 'org-noter)

(setq org-noter-separate-notes-from-heading nil)
(setq org-noter-auto-save-last-location t)
(setq org-noter-doc-property-in-notes t)
(setq org-noter-notes-search-path '("~/org"))
(setq org-noter-default-notes-file-names '("notes.org"))

(toggle-frame-fullscreen)
;(find-file "~/org/notes.org")
(split-window-right)
(find-file "~/Downloads/xxxxxxxxxxxxxxx.epub")
(nov-render-document)




It would be nice if org-noter would handle nov-mode.

Thanks for looking into this, Gregor

**Comment by weirdNox** [comment]
I'll look into your issue, thanks for the report! I don't personally annotate epubs, so this is probably a bug I made in recent updates.

I won't probably look into this until Thursday, though!

**Comment by licebmi** [comment]
Just stumbled with the same issue after upgrading, so I think it's safe to assume this was due a recent update.

I got this traceback here:
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p (6 . 6120))
  org-noter--note-after-tipping-point(0.3 (6 . 1102) [nov (6 . 1) (6 . 6120)])
  #f(compiled-function (headline) #<bytecode 0x242b8e9>)((headline (:raw-value "xxxxx" :begin 157 :end 489 :pre-blank 0 :contents-begin 438 :contents-end 489 :level 2 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 157 :NOTER_PAGE "(6 . 1102)" :title "xxxxx" :parent (headline (:raw-value "Bullshit Jobs_ A Theory - David Graeber" :begin 1 :end 489 :pre-blank 0 :contents-begin 43 :contents-end 489 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 1 :NOTER_PAGE "(6 . 23029)" :NOTER_DOCUMENT "Bullshit Jobs_ A Theory - David Graeber.epub" :title "Bullshit Jobs_ A Theory - David Graeber" :parent (org-data nil #3)) (section (:begin 43 :end 157 :contents-begin 43 :contents-end 157 :post-blank 0 :post-affiliated 43 :parent #3) (property-drawer (:begin 43 :end 157 :contents-begin 58 :contents-end 149 :post-blank 0 :post-affiliated 43 :parent #4))) #1)) (section (:begin 438 :end 489 :contents-begin 438 :contents-end 489 :post-blank 0 :post-affiliated 438 :parent #1) (property-drawer (:begin 438 :end 489 :contents-begin 454 :contents-end 481 :post-blank 0 :post-affiliated 438 :parent #2)))))
  #f(compiled-function (--data) #<bytecode 0x242ace9>)((headline (:raw-value "xxxxx" :begin 157 :end 489 :pre-blank 0 :contents-begin 438 :contents-end 489 :level 2 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 157 :NOTER_PAGE "(6 . 1102)" :title "xxxxx" :parent (headline (:raw-value "Bullshit Jobs_ A Theory - David Graeber" :begin 1 :end 489 :pre-blank 0 :contents-begin 43 :contents-end 489 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 1 :NOTER_PAGE "(6 . 23029)" :NOTER_DOCUMENT "Bullshit Jobs_ A Theory - David Graeber.epub" :title "Bullshit Jobs_ A Theory - David Graeber" :parent (org-data nil #3)) (section (:begin 43 :end 157 :contents-begin 43 :contents-end 157 :post-blank 0 :post-affiliated 43 :parent #3) (property-drawer (:begin 43 :end 157 :contents-begin 58 :contents-end 149 :post-blank 0 :post-affiliated 43 :parent #4))) #1)) (section (:begin 438 :end 489 :contents-begin 438 :contents-end 489 :post-blank 0 :post-affiliated 438 :parent #1) (property-drawer (:begin 438 :end 489 :contents-begin 454 :contents-end 481 :post-blank 0 :post-affiliated 438 :parent #2)))))
  mapc(#f(compiled-function (--data) #<bytecode 0x242ace9>) ((section (:begin 43 :end 157 :contents-begin 43 :contents-end 157 :post-blank 0 :post-affiliated 43 :parent (headline (:raw-value "Bullshit Jobs_ A Theory - David Graeber" :begin 1 :end 489 :pre-blank 0 :contents-begin 43 :contents-end 489 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 1 :NOTER_PAGE "(6 . 23029)" :NOTER_DOCUMENT "Bullshit Jobs_ A Theory - David Graeber.epub" :title "Bullshit Jobs_ A Theory - David Graeber" :parent (org-data nil #4)) . #1)) (property-drawer (:begin 43 :end 157 :contents-begin 58 :contents-end 149 :post-blank 0 :post-affiliated 43 :parent #2))) (headline (:raw-value "xxxxx" :begin 157 :end 489 :pre-blank 0 :contents-begin 438 :contents-end 489 :level 2 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 157 :NOTER_PAGE "(6 . 1102)" :title "xxxxx" :parent (headline (:raw-value "Bullshit Jobs_ A Theory - David Graeber" :begin 1 :end 489 :pre-blank 0 :contents-begin 43 :contents-end 489 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 1 :NOTER_PAGE "(6 . 23029)" :NOTER_DOCUMENT "Bullshit Jobs_ A Theory - David Graeber.epub" :title "Bullshit Jobs_ A Theory - David Graeber" :parent (org-data nil #4)) . #1)) (section (:begin 438 :end 489 :contents-begin 438 :contents-end 489 :post-blank 0 :post-affiliated 438 :parent #2) (property-drawer (:begin 438 :end 489 :contents-begin 454 :contents-end 481 :post-blank 0 :post-affiliated 438 :parent #3))))))
  #f(compiled-function (--data) #<bytecode 0x242ace9>)(((section (:begin 43 :end 157 :contents-begin 43 :contents-end 157 :post-blank 0 :post-affiliated 43 :parent (headline (:raw-value "Bullshit Jobs_ A Theory - David Graeber" :begin 1 :end 489 :pre-blank 0 :contents-begin 43 :contents-end 489 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 1 :NOTER_PAGE "(6 . 23029)" :NOTER_DOCUMENT "Bullshit Jobs_ A Theory - David Graeber.epub" :title "Bullshit Jobs_ A Theory - David Graeber" :parent (org-data nil #4)) . #1)) (property-drawer (:begin 43 :end 157 :contents-begin 58 :contents-end 149 :post-blank 0 :post-affiliated 43 :parent #2))) (headline (:raw-value "xxxxx" :begin 157 :end 489 :pre-blank 0 :contents-begin 438 :contents-end 489 :level 2 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 157 :NOTER_PAGE "(6 . 1102)" :title "xxxxx" :parent (headline (:raw-value "Bullshit Jobs_ A Theory - David Graeber" :begin 1 :end 489 :pre-blank 0 :contents-begin 43 :contents-end 489 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 1 :NOTER_PAGE "(6 . 23029)" :NOTER_DOCUMENT "Bullshit Jobs_ A Theory - David Graeber.epub" :title "Bullshit Jobs_ A Theory - David Graeber" :parent (org-data nil #4)) . #1)) (section (:begin 438 :end 489 :contents-begin 438 :contents-end 489 :post-blank 0 :post-affiliated 438 :parent #2) (property-drawer (:begin 438 :end 489 :contents-begin 454 :contents-end 481 :post-blank 0 :post-affiliated 438 :parent #3))))))
  org-element-map(((section (:begin 43 :end 157 :contents-begin 43 :contents-end 157 :post-blank 0 :post-affiliated 43 :parent (headline (:raw-value "Bullshit Jobs_ A Theory - David Graeber" :begin 1 :end 489 :pre-blank 0 :contents-begin 43 :contents-end 489 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 1 :NOTER_PAGE "(6 . 23029)" :NOTER_DOCUMENT "Bullshit Jobs_ A Theory - David Graeber.epub" :title "Bullshit Jobs_ A Theory - David Graeber" :parent (org-data nil #4)) . #1)) (property-drawer (:begin 43 :end 157 :contents-begin 58 :contents-end 149 :post-blank 0 :post-affiliated 43 :parent #2))) (headline (:raw-value "xxxxx" :begin 157 :end 489 :pre-blank 0 :contents-begin 438 :contents-end 489 :level 2 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 157 :NOTER_PAGE "(6 . 1102)" :title "xxxxx" :parent (headline (:raw-value "Bullshit Jobs_ A Theory - David Graeber" :begin 1 :end 489 :pre-blank 0 :contents-begin 43 :contents-end 489 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 1 :NOTER_PAGE "(6 . 23029)" :NOTER_DOCUMENT "Bullshit Jobs_ A Theory - David Graeber.epub" :title "Bullshit Jobs_ A Theory - David Graeber" :parent (org-data nil #4)) . #1)) (section (:begin 438 :end 489 :contents-begin 438 :contents-end 489 :post-blank 0 :post-affiliated 438 :parent #2) (property-drawer (:begin 438 :end 489 :contents-begin 454 :contents-end 481 :post-blank 0 :post-affiliated 438 :parent #3))))) headline #f(compiled-function (headline) #<bytecode 0x242b8e9>) nil nil (babel-call center-block clock comment comment-block diary-sexp drawer dynamic-block example-block export-block fixed-width footnote-definition horizontal-rule inlinetask item keyword latex-environment node-property paragraph plain-list planning property-drawer quote-block section special-block src-block table table-row verse-block))
  org-noter--get-view-info([nov (6 . 1) (6 . 6120)] (6 . 3182))
  org-noter-insert-note(3182)
  org-noter-insert-precise-note(nil)
  funcall-interactively(org-noter-insert-precise-note nil)
  call-interactively(org-noter-insert-precise-note nil nil)
  command-execute(org-noter-insert-precise-note)
