### ISSUE TITLE
Need an ID on new note entries (for org-brain)

### ISSUE THREAD

**Issue by rosetree** [weirdNox/org-noter#62]
Recently I combined `org-noter` with the also wonderful [`org-brain` wiki and concept mapping package](https://github.com/Kungsgeten/org-brain/). This setup allows me to organize the documents in a map and have all notes attached to them in their hierarchy. 

`org-brain` only shows entries that have an ID. So it would be great if there was an `org-noter-insert-heading-hook` where I could just add `org-id-get-create`. This could look similar to the configuration in #20, with the exception that my suggestion could limit the ID creation to `org-noter` notes.

What do you think? Could this be done in `org-noter` or should I use the `org-insert-heading-hook` instead?

**Comment by weirdNox** [comment]
Ok, this is doable!

**Comment by weirdNox** [comment]
Could you try and see if it works? Just committed it :)

**Comment by rosetree** [comment]
``` elisp
(add-hook 'org-noter-insert-heading-hook #'org-id-get-create)
```
works as expected! Thanks, for your fast response.

**Comment by randomwangran** [comment]
just add a commit id to what changes to this issue: https://github.com/weirdNox/org-noter/commit/f6f7a8d3af1c3e7e26173b245ba4a95e3cf03074
