### ISSUE TITLE
Org-Noter and Previous Interleave org file

### ISSUE THREAD

**Issue by petemcd18** [weirdNox/org-noter#68]
MWE:

**START OF init.el** 

```

(setq org-noter-property-doc-file "INTERLEAVE_PDF"
      org-noter-property-note-location "INTERLEAVE_PAGE_NOTE")
(setq org-noter-notes-window-location 'vertical-split)

(custom-set-variables

'(org-noter-notes-search-path (quote ("~/Documents/notes/"))))

```

**END OF init.el**

**brickell.pdf** located ("~/Documents/pdfs/brickell2017.pdf)

**brickell.org** located ("~/Documents/notes/brickell2017.org)

**START of brickell.org**

```
#+TITLE: Notes on: K. Brickell, &  others (2017): Geographies of forced eviction: dispossession, violence, resistance
#+INTERLEAVE_PDF: /Volumes/ENCSTICK01/Bibliography/pdfs/brickell2017.pdf
* Notes for page 3
  :PROPERTIES:
  :interleave_page_note: 3
  :END:
These are my notes for this page
* Notes for page 10
  :PROPERTIES:
  :interleave_page_note: 10
  :END:
test for this page
* Notes for Page 12
  :PROPERTIES:
  :interleave_page_note: 12
  :END:
Test for page 12
```
**END of brickell.org**

===
Method.
1. Open Emacs with init.el loaded
2. Open brickell2017.pdf
3. Once opened with PDF-Tools inside emacs I run:

`M-x org-noter`

This opens a buffer horizontally below: (see attached screenshot)
<img width="1680" alt="Screenshot 2019-04-24 at 23 46 11" src="https://user-images.githubusercontent.com/43674504/56699188-71425b80-66ec-11e9-96e7-1f38191e99b4.png">

It fails to load the contents of the note file but inside the buffer creates and then immediately writes out to ~/Documents/notes/brickell2017.org

```
* brickell2017
  :PROPERTIES:
  :INTERLEAVE_PDF: ../pdfs/brickell2017.pdf
  :END:
```

When then viewing my original file as I assumed it had overwritten it without a prompt it had not overwritten but had appended to the file and the output of the file is now:

```
#+TITLE: Notes on: K. Brickell, &  others (2017): Geographies of forced eviction: dispossession, violence, resistance
#+INTERLEAVE_PDF: ~/Documents/pdfs/brickell2017.pdf
* Notes for page 3
  :PROPERTIES:
  :interleave_page_note: 3
  :END:
These are my notes for this page
* Notes for page 10
  :PROPERTIES:
  :interleave_page_note: 10
  :END:
test for this page
* Notes for Page 12
  :PROPERTIES:
  :interleave_page_note: 12
  :END:
Test for page 12

* brickell2017
  :PROPERTIES:
  :INTERLEAVE_PDF: ../pdfs/brickell2017.pdf
  :END:

```

I exited emacs and reopened the pdf and ran M-x org-noter
it loaded only

```

* brickell2017
  :PROPERTIES:
  :INTERLEAVE_PDF: ../pdfs/brickell2017.pdf
  :END:
```

but yet if I open the ~/Documents/notes/brickell.org file in a plain text editor like TextEdit
this is the contents:

```
#+TITLE: Notes on: K. Brickell, &  others (2017): Geographies of forced eviction: dispossession, violence, resistance
#+INTERLEAVE_PDF: ~/Documents/pdfs/brickell2017.pdf
* Notes for page 3
  :PROPERTIES:
  :interleave_page_note: 3
  :END:
These are my notes for this page
* Notes for page 10
  :PROPERTIES:
  :interleave_page_note: 10
  :END:
test for this page
* Notes for Page 12
  :PROPERTIES:
  :interleave_page_note: 12
  :END:
Test for page 12

* brickell2017
  :PROPERTIES:
  :INTERLEAVE_PDF: ../pdfs/brickell2017.pdf
  :END:
```

This is the same on any PDF and associated and corresponding note file.
pdf always authoryear.pdf
notes file always the same name but with .org extension so authoryear.org

Any help would be appreciated as I'm at an absolute loss.

**Comment by weirdNox** [comment]
Hello :)
This is expected from `org-noter`. In Emacs, it is called [narrowing](https://www.gnu.org/software/emacs/manual/html_node/emacs/Narrowing.html). 
The idea is that you have all your notes in a file, but when viewing a PDF, only the relevant notes are shown. Notice that you can always view the entire notes file in its buffer (when in a session, you'll have the buffer `brickell.org` and the buffer `Notes of ...`). So, if you want to see all notes, you can open the buffer `brickell.org` and they will be there.

The buffer you are seeing is called an [indirect buffer](https://www.gnu.org/software/emacs/manual/html_node/emacs/Indirect-Buffers.html): the contents are the same as the original (and they are kept in sync, changing one changes the other), but its properties may be different (in this case, the view is narrowed to the relevant notes)

**Comment by petemcd18** [comment]
I appreciate Narrowing but my point is that none of my previous notes are visible at all as i move through using p and n keys on the pdf.
Essentially what I am saying is in any previous Interleaving note file I would have to manually recreate them for them to work with org-noter which defeats the purpose of setting the variables?

Surely this is not a feature by design?

**Comment by weirdNox** [comment]
Oh, sorry, I'm a bit tired so I didn't realize that is was creating a repeated heading! I'll try to see what's happening

**Comment by petemcd18** [comment]
No problem there is no rush. Please get some rest and when you have chance I'd be grateful to hear from you.

**Comment by weirdNox** [comment]
Ah! I see, the problem is that org-noter does not support annotating documents without headings.

Interleave had two modes, the multi-pdf mode and the one you are using. Org-noter is only compatible with the former.

If you want to use `org-noter`, what I would do is a keyboard macro that converts that first `INTERLEAVE_PDF` line into an heading with that property and then demote all the other headings to be inside it.

I took your example file and created a keyboard macro that converts the interleave properties to org-noter properties and creates the parent heading too.
```elisp
(fset 'convert-interleave-to-org-noter
      (lambda (&optional arg)
	"Keyboard macro."
	(interactive "p")
	(kmacro-exec-ring-item
	 '([134217788 134217765 105 110 116 101 114 108 101 97 118 101 95 112 97 103 101 95 110 111 116 101 return 110 111 backspace backspace 78 79 84 69 82 95 80 65 71 69 return 33 134217788 134217765 105 110 116 101 114 108 101 97 118 101 95 112 97 backspace 100 102 return 78 79 84 69 82 95 68 79 67 85 77 69 78 84 return 33 1 6 6 backspace backspace 42 32 return 58 80 82 79 80 69 82 84 73 69 83 58 return 58 5 return 58 69 78 68 58 16 5 134217826 2 67108896 134217730 134217734 134217826 134217847 16 16 25 14 14 67108896 134217790 134217848 111 114 103 45 100 111 45 100 101 109 tab return] 0 "%d")
	 arg)))
```

The code looks obfuscated because it was created by Emacs from my keyboard macro. If you use it, please make sure it doesn't delete any important data from your files!

You may run this by evaluating it with `M-:` and then executing `M-x convert-interleave-to-org-noter`

**Comment by weirdNox** [comment]
As this converts the properties too, you should remove this from your init
```elisp
(setq org-noter-property-doc-file "INTERLEAVE_PDF"
      org-noter-property-note-location "INTERLEAVE_PAGE_NOTE")
```

**Comment by petemcd18** [comment]
Hi, 

This works perfectly. Many thanks for your help. I have no idea what that keyboard macro code is doing as sadly I cannot work out what all them numbers mean or relate to.  So can I just check whether in theory (subject to me checking a few files in isolation) this keyboard macro would work with similarly formatted interleave note files ie formatted exactly the same as the example above but obviously different notes on different pages of a pdf. 

Really appreciate your efforts on this project and thank you again for the help.

**Comment by weirdNox** [comment]
You're welcome :)
Yes, if the remaining files are like this one, this probably works.
This goes to the top of the page, replaces all INTERLEAVE_..., goes to the top, searches for the PDF property, converts it into and heading then selects everything below and runs `org-do-demote`.

Macros are amazing, by default you start them with F3, do your stuff and then F4, and you may run it repeatedly by clicking F4.
You just have to pay attention in order to do generic stuff, like not going forward 4 times because in one case you have a word with 4 letters, it would work best to do forward-word instead, as it works for all sizes!

**Comment by weirdNox** [comment]
Btw, if you want, you may try to create your own macro that does this, and try to include the title in the heading directly, as I only noticed you had the title there after doing the macro :P

**Comment by weirdNox** [comment]
I believe this is done, right? Feel free to reopen it if not! :)
