### ISSUE TITLE
pdf-tools error though it's installed

### ISSUE THREAD

**Issue by Nathan-Furnal** [weirdNox/org-noter#78]
Hi all, 

I'm currently using emacs 26.1 on Ubuntu 19.04 and I install packages using MELPA.

When I click 'Install' on org-noter after `list-packages`  I get the following error :

``
org-noter-integration.el:2:1:Error: Cannot open load file: No such file or directory, org-pdftools
``

But I do have pdf-tools installed. More, the package is written as "installed" afterwards.

**Comment by weirdNox** [comment]
Oh no, that's a mistake I made when integrating a pull request recently, I thought that file wouldn't be included in the package! I'll fix it, in a few hours try again please :)

**Comment by weirdNox** [comment]
Also, even though it gives that error installing, you may probably use `org-noter` anyway, as it is on a different file

**Comment by Nathan-Furnal** [comment]
Sure thing ! Thanks for heads-up. Do you want me to close it or do you want to add it to a PR ?

**Comment by weirdNox** [comment]
I believe commit 73a6c85dcdb6579d7ff183558a5be580926ce043 fixes this. 
After MELPA rebuilds the package, try to upgrade and see if it works. Then, please, close or comment depending on whether or not this works :)

**Comment by Nathan-Furnal** [comment]
All good thank you !
