### ISSUE TITLE
Quitting session with the solo frame emitting an error

### ISSUE THREAD

**Issue by xiangsheng** [weirdNox/org-noter#79]
When setting `org-noter-always-create-frame` to `nil` and having only one session, if I try to use `q` to quit the session, equivalently use `org-noter-kill-session`, the emacs always complains that `(error "Attempt to delete the sole visible or iconified frame")`. 

I suppose that `org-noter-kill-session` maybe forget to take `org-noter-always-create-frame` into consideration so that it always tries to kill the frame. Am I right?

**Comment by weirdNox** [comment]
Hi there!
Are you using the latest version? I am not able to reproduce this problem, it works correctly for me.
Could you obtain a backtrace with `toggle-debug-on-error`?

**Comment by xiangsheng** [comment]
Yes, I use the latest version.  Here is the backtrace.

```
Debugger entered--Lisp error: (error "Attempt to delete the sole visible or iconified frame")
  delete-frame(#<frame Emacs Org-noter - Gaifullin_2010aa 0x11b6df0>)
  org-noter-kill-session(nil)
  funcall-interactively(org-noter-kill-session nil)
  call-interactively(org-noter-kill-session nil nil)
  command-execute(org-noter-kill-session)
```

**Comment by weirdNox** [comment]
Ok, I use Emacs as a server, so I don't get the error even if I run `(delete-frame)` on the only opened frame.
That said, manually opening Emacs without using the server, I was able to obtain the error only when only the notes window was visible (without the PDF window) and when executing `(org-noter-kill-session)` directly.
I've pushed https://github.com/weirdNox/org-noter/commit/e1273c8ecb172012caaf14f50b41305e16e893e3, but as I am not sure if that's your problem, please report back :)

**Comment by xiangsheng** [comment]
Good job! I don't see the error any more.

Another (possible foolish) suggestion on the behavior of killing sessions. I see that when the only session of a PDF file is killed, the PDF file is always left opened even if the PDF file is not opened before the org-noter session. Perhaps it is a little more reasonable to kill a session and close the PDF file if the PDF file is not open before the session. Of course, if the PDF is opened before the session, we just leave the PDF open when killing the session.  Or a variable can be provided to decide whether a PDF file is closed when all sessions are killed.

It may be helpful to preventing us from opening too many PDF buffers when we switch from one PDF to another PDF.

**Comment by xiangsheng** [comment]
Errr, I encounter the same error again.

After the emacs is stated, if I just open a new org-noter session, do nothing and killing the session, no error appears now. But If after opening the session, I do anything, for example, inserting a new note in the org file or adding an underline to the pdf, then save and kill the session, the same error appear again. The backtrace is the same as I pasted before. 

Strangely enough, once the error appears, now if I open another session, do nothing and kill the session, not like the fresh start case, the error still appears!

**Comment by weirdNox** [comment]
Oh, bummer. I just remembered something, I believe you can enhance the backtrace by going to the function in question `org-noter-kill-session` and evaluating it (with `C-M-x` or `M-x eval-defun`). Now, when the error is raised, the backtrace should have the precise location of where it happened.

**Comment by weirdNox** [comment]
> Another (possible foolish) suggestion on the behavior of killing sessions. I see that when the only session of a PDF file is killed, the PDF file is always left opened even if the PDF file is not opened before the org-noter session. Perhaps it is a little more reasonable to kill a session and close the PDF file if the PDF file is not open before the session. Of course, if the PDF is opened before the session, we just leave the PDF open when killing the session. Or a variable can be provided to decide whether a PDF file is closed when all sessions are killed.

Ok, when this is solved, I'll try to implement that :)

**Comment by xiangsheng** [comment]
I think I know the reason for the error.  `org-noter-kill-session` may have some collision with the input method package [pyim](https://github.com/tumashu/pyim) I'm using. More precisely,  the error occurs because`pyim` use another package [posframe](https://github.com/tumashu/posframe) to draw the candidate boxes. Basically, such candidate boxes are small (child) frames. The problem is when the input is finished, these frames are not killed but just hided! So when `org-noter-kill-session` is invoked, perhaps wrong number of frames is counted. If I use `posframe-delete-all` to delete all posframe frames before using `org-noter-kill-session`, the error seems gone. Maybe I should advice `org-noter-kill-session` to workaround this problem. 

Anyway, the detailed backtrace is as follows.

```elisp
Debugger entered--Lisp error: (error "Attempt to delete the sole visible or iconified frame")
  delete-frame(#<frame Emacs Org-noter - Chern_1974aa 0x11bbc30>)
  (if (or (= (length (frames-on-display-list)) 1) (not org-noter-kill-frame-at-session-end)) (progn (delete-other-windows) (set-frame-parameter nil (quote name) nil)) (delete-frame frame))
  (progn (if (or (= (length (frames-on-display-list)) 1) (not org-noter-kill-frame-at-session-end)) (progn (delete-other-windows) (set-frame-parameter nil (quote name) nil)) (delete-frame frame)))
  (if (frame-live-p frame) (progn (if (or (= (length (frames-on-display-list)) 1) (not org-noter-kill-frame-at-session-end)) (progn (delete-other-windows) (set-frame-parameter nil (quote name) nil)) (delete-frame frame))))
  (let* ((ast (org-noter--parse-root session)) (frame (progn (or (and (memq (type-of session) cl-struct-org-noter--session-tags) t) (signal (quote wrong-type-argument) (list (quote org-noter--session) session))) (aref session 2))) (notes-buffer (progn (or (and (memq (type-of session) cl-struct-org-noter--session-tags) t) (signal (quote wrong-type-argument) (list (quote org-noter--session) session))) (aref session 4))) (base-buffer (buffer-base-buffer notes-buffer)) (notes-modified (buffer-modified-p base-buffer)) (doc-buffer (progn (or (and (memq (type-of session) cl-struct-org-noter--session-tags) t) (signal (quote wrong-type-argument) (list (quote org-noter--session) session))) (aref session 3)))) (let ((--dolist-tail-- (get-buffer-window-list notes-buffer nil t))) (while --dolist-tail-- (let ((window (car --dolist-tail--))) (let ((old-frame (selected-frame)) (old-buffer (current-buffer))) (unwind-protect (progn (select-frame ... ...) (if ... ... ...)) (if (frame-live-p old-frame) (progn ...)) (if (buffer-live-p old-buffer) (progn ...)))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (save-current-buffer (set-buffer notes-buffer) (remove-hook (quote kill-buffer-hook) (quote org-noter--handle-kill-buffer) t) (restore-buffer-modified-p nil)) (kill-buffer notes-buffer) (save-current-buffer (set-buffer base-buffer) (org-noter--unset-text-properties ast) (set-buffer-modified-p notes-modified)) (save-current-buffer (set-buffer doc-buffer) (remove-hook (quote kill-buffer-hook) (quote org-noter--handle-kill-buffer) t)) (kill-buffer doc-buffer) (if (frame-live-p frame) (progn (if (or (= (length (frames-on-display-list)) 1) (not org-noter-kill-frame-at-session-end)) (progn (delete-other-windows) (set-frame-parameter nil (quote name) nil)) (delete-frame frame)))))
  (progn (setq org-noter--sessions (delq session org-noter--sessions)) (if (eq (length org-noter--sessions) 0) (progn (remove-hook (quote delete-frame-functions) (quote org-noter--handle-delete-frame)) (advice-remove (quote doc-view-goto-page) (quote org-noter--location-change-advice)) (advice-remove (quote nov-render-document) (quote org-noter--nov-scroll-handler)))) (let* ((ast (org-noter--parse-root session)) (frame (progn (or (and (memq ... cl-struct-org-noter--session-tags) t) (signal (quote wrong-type-argument) (list ... session))) (aref session 2))) (notes-buffer (progn (or (and (memq ... cl-struct-org-noter--session-tags) t) (signal (quote wrong-type-argument) (list ... session))) (aref session 4))) (base-buffer (buffer-base-buffer notes-buffer)) (notes-modified (buffer-modified-p base-buffer)) (doc-buffer (progn (or (and (memq ... cl-struct-org-noter--session-tags) t) (signal (quote wrong-type-argument) (list ... session))) (aref session 3)))) (let ((--dolist-tail-- (get-buffer-window-list notes-buffer nil t))) (while --dolist-tail-- (let ((window (car --dolist-tail--))) (let ((old-frame ...) (old-buffer ...)) (unwind-protect (progn ... ...) (if ... ...) (if ... ...))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (save-current-buffer (set-buffer notes-buffer) (remove-hook (quote kill-buffer-hook) (quote org-noter--handle-kill-buffer) t) (restore-buffer-modified-p nil)) (kill-buffer notes-buffer) (save-current-buffer (set-buffer base-buffer) (org-noter--unset-text-properties ast) (set-buffer-modified-p notes-modified)) (save-current-buffer (set-buffer doc-buffer) (remove-hook (quote kill-buffer-hook) (quote org-noter--handle-kill-buffer) t)) (kill-buffer doc-buffer) (if (frame-live-p frame) (progn (if (or (= (length ...) 1) (not org-noter-kill-frame-at-session-end)) (progn (delete-other-windows) (set-frame-parameter nil (quote name) nil)) (delete-frame frame))))))
  (if (and session (memq session org-noter--sessions)) (progn (setq org-noter--sessions (delq session org-noter--sessions)) (if (eq (length org-noter--sessions) 0) (progn (remove-hook (quote delete-frame-functions) (quote org-noter--handle-delete-frame)) (advice-remove (quote doc-view-goto-page) (quote org-noter--location-change-advice)) (advice-remove (quote nov-render-document) (quote org-noter--nov-scroll-handler)))) (let* ((ast (org-noter--parse-root session)) (frame (progn (or (and ... t) (signal ... ...)) (aref session 2))) (notes-buffer (progn (or (and ... t) (signal ... ...)) (aref session 4))) (base-buffer (buffer-base-buffer notes-buffer)) (notes-modified (buffer-modified-p base-buffer)) (doc-buffer (progn (or (and ... t) (signal ... ...)) (aref session 3)))) (let ((--dolist-tail-- (get-buffer-window-list notes-buffer nil t))) (while --dolist-tail-- (let ((window ...)) (let (... ...) (unwind-protect ... ... ...)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (save-current-buffer (set-buffer notes-buffer) (remove-hook (quote kill-buffer-hook) (quote org-noter--handle-kill-buffer) t) (restore-buffer-modified-p nil)) (kill-buffer notes-buffer) (save-current-buffer (set-buffer base-buffer) (org-noter--unset-text-properties ast) (set-buffer-modified-p notes-modified)) (save-current-buffer (set-buffer doc-buffer) (remove-hook (quote kill-buffer-hook) (quote org-noter--handle-kill-buffer) t)) (kill-buffer doc-buffer) (if (frame-live-p frame) (progn (if (or (= ... 1) (not org-noter-kill-frame-at-session-end)) (progn (delete-other-windows) (set-frame-parameter nil ... nil)) (delete-frame frame)))))))
  org-noter-kill-session(nil)
  funcall-interactively(org-noter-kill-session nil)
  call-interactively(org-noter-kill-session nil nil)
  command-execute(org-noter-kill-session)
```

**Comment by weirdNox** [comment]
Ohhh, that must be it, they must appear in `(frames-on-display-list)` but they do not make Emacs survive on their own, so... I'll try to see if I can come up with something.

**Comment by weirdNox** [comment]
I have just taken a look at posframe source, and found that it puts the original frame as parent frame, and that must be the problem, because, from [the manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Child-Frames.html):
> When a parent frame is about to be deleted (see Deleting Frames), its child frames are recursively deleted before it.

**Comment by weirdNox** [comment]
I'm pretty sure this is fixed :) 
I took a look at [the Emacs source code](https://github.com/emacs-mirror/emacs/blob/897540069fb09d091802046046daca821079aac5/src/frame.c#L1751) and saw how they implemented the verification (which was what I expected).

I also did some tests with posframe and it seemed to work :D

**Comment by xiangsheng** [comment]
Now, it's not error about frame but window... If only one frame appears, when kill the session, no error. If I have several sessions, therefore several frames, when kill a session, the error appears. Besides the error message, I find the pdf buffer associated to the org-noter session is not closed properly.

Backtrace
```elisp
Debugger entered--Lisp error: (error "#<window 81> is not a live window")
  signal(error ("#<window 81> is not a live window"))
  error("%s is not a live window" #<window 81>)
  window-normalize-window(#<window 81> t)
  unrecord-window-buffer(#<window 81> #<buffer Atiyah_1975ab>)
  replace-buffer-in-windows(#<buffer Atiyah_1975ab>)
  kill-buffer(#<buffer Atiyah_1975ab>)
  org-noter-kill-session(nil)
  funcall-interactively(org-noter-kill-session nil)
  call-interactively(org-noter-kill-session nil nil)
  command-execute(org-noter-kill-session)
```
Still, running `posframe-delete-all` will fix this.
