### ISSUE TITLE
Extracting outline (with page number as org-noter properties) as a skeleton for new document

### ISSUE THREAD

**Issue by usharf** [weirdNox/org-noter#8]
Would this be possible? I often scan and edit the outline of documents I need and organize my notes around headlines in the source. Would be great if the outline could be extracted automatically and be used as a skeleton for a new notes file managed with `org-noter`.

The outline meta data is visible with `pdftk`, for example:
```sh
pdftk in.pdf dump_data_utf8 output out.txt
```

PS I manually add my own outline using `pdfoutline` utility (bundled with  `fntsample`):

```sh
perl pdfoutline.pl in.pdf OUTLINE.txt out.pdf
```

**Comment by weirdNox** [comment]
Yes, this would certainly be possible, `pdf-tools` has it, and I think we could leverage it. I'll take a look :)
