### ISSUE TITLE
save the last location of a PDF file does work 

### ISSUE THREAD

**Issue by cryoguy** [weirdNox/org-noter#80]
Thanks for the wonderful package!  

This maybe a silly question.   How does save-last-location work in  a PDF file?  Am I supposed to open it from notes file or simply just open the PDF file?   In my case, Emacs remembers the last location in epub files, but not in PDF files after setting org-noter-auto-save-last-location to non-nil. I am using PDF-tools with Emacs 25.3 in Arch linux.

**Comment by weirdNox** [comment]
Hi! 
This variable only affects the behavior when you open the PDF with the command `org-noter` from the notes file. I suppose nov.el has the mechanism itself for storing the last page, so you have it even when you are not using org-noter.

**Comment by cryoguy** [comment]
got it thanks!
