### ISSUE TITLE
org-noter-doc-property-in-notes breaks movement commands

### ISSUE THREAD

**Issue by algoterranean** [weirdNox/org-noter#84]
I ran into a problem where, when using org-noter, I wasn't able to move between notes. This includes the functions bound to `M-p` `M-n` `C-M-p` and `C-M-n`, all of them would fail with a "no next/previous note", even though there were clearly multiple notes. This occurred when I had one PDF per notes file, multiple PDFs per notes file, whether I was using a minimal startup (`-Q`) or not, and so on.

I seem to have traced it back to `org-noter-doc-property-in-notes`. This is the config I was using when I ran into issues:

```
(use-package org-noter
  :config
  (setq org-noter-default-notes-file-names '("notes.org")
        org-noter-notes-search-path '("~/org/notes")
        org-noter-separate-notes-from-heading t
        org-noter-always-create-frame nil
        org-noter-auto-save-last-location t
        org-noter-doc-property-in-notes t
        )
  :bind
  (([C-return] . other-window)))
```

When I removed the setting of `org-noter-doc-property-in-notes`, all the movement commands worked fine.

This is on emacs 26.1 on linux, using org-noter 20191015.2147.

**Comment by weirdNox** [comment]
I believe this is fixed! Thanks for the report :D
