### ISSUE TITLE
Extract citation with precise note

### ISSUE THREAD

**Issue by bepolymathe** [weirdNox/org-noter#88]
Hi, 

First of all, thank you for this wonderful package. 

As a social scientist, I need to read and annotate many PDFs but also interviews. For more stability, I transform the interviews into PDF so that I can annotate them. 

In my work process, I need to be able to return it to the original quote (org-noter is perfect for that) but also extract the exact passage in the text. 

Currently, I have two solutions: 
1. Either I read the document with pdftools, highlight it, save it, then open Org-note and extract the skeleton. This is quite correct... unless I need to highlight a new passage after this skeleton creation. In this case, you have to re-import everything and often this creates problems because the document has been modified. 
2. Either I highlight a passage in the document with the mouse and insert a precise note. In this case, it suggests extracting the highlighted text but only as the title of the note (and not as content). With this config `(setq org-noter-insert-selected-text-inside-note t)` 

In both cases, the next step for me is to code citations with tags in org-mode and then do precise searches that combine codes. The ideal therefore does not exist at this stage. 

Would it be possible to consider that solution "2" integrates the content of the quotation not as the title of the note but as the content? Something like `org-noter-insert-selected-text-inside-note-content`

Have a good day !

**Comment by bepolymathe** [comment]
What do you think about that ?

**Comment by bepolymathe** [comment]
Happy new year ! And thanks for this useful package 👍

**Comment by seanvert** [comment]
```
(defun org-noter-insert-selected-text-inside-note-content ()
  (progn (setq currenb (buffer-name))
		 (org-noter-insert-precise-note)
		 (set-buffer currenb)
		 (org-noter-insert-note)))
```

You can use this function. It asks for whatever you want in the title, if you press enter it will behave like the normal one and insert the selection as the title, and it functions the same with the contents. Just bind it to a button, select a text area, press it and press enter two times. You'll get a precise note with both title and contents equal to the text.

**Comment by bepolymathe** [comment]
Oh... thank you for that answer! The year 2020 is off to a good start ;-)
I'm gonna try this. What's the cleanest way to associate a key with a function only in pdftools?
Have a nice day.

**Comment by seanvert** [comment]
This is a decent way to do it, like `(define-key pdf-view-mode-map (kdb "y") 'org-noter-insert-selected-text-inside-note-content)`. You can also add modifiers if you prefer, like "C-y", "M-y" or something. Just put that line somewhere in your init.el file after the pdf-tools and after the function definition.

That function above is somewhat sloppy, because I'm not that skilled in elisp, but I think it will work.

**Comment by bepolymathe** [comment]
Ok, thanks. 
I have test it (and I simply corrected the syntax error... "kdb" --» "kbd") but i have an error :

`command-execute: Wrong type argument: commandp, org-noter-insert-selected-text-inside-note-content`

**Comment by seanvert** [comment]
Oh, I forgot to put that interactive part, otherwise it will only work inside the repl.

This one really works 

```
(defun org-noter-insert-selected-text-inside-note-content ()
  (interactive)
  (progn (setq currenb (buffer-name))
		 (org-noter-insert-precise-note)
		 (set-buffer currenb)
		 (org-noter-insert-note)))

```

Every time you create some command that you'll use with M-x you'll have to put it there. I don't remember why, but there are different types of it too.

**Comment by bepolymathe** [comment]
It actually works better that way ;-) 
Thanks to you.

**Comment by wuqui** [comment]
Thanks a lot, that's very useful!

Could you give me a hint how to modify this to optimize this a little? I would like to ...

1. have the extracted text inserted within a `#+begin_quote` block.
2. get rid of the initial empty line following the properties drawer.

**Comment by seanvert** [comment]
> Thanks a lot, that's very useful!
> 
> Could you give me a hint how to modify this to optimize this a little? I would like to ...
> 
> 1. have the extracted text inserted within a `#+begin_quote` block.
> 2. get rid of the initial empty line following the properties drawer.

That one that I made uses both the `org-noter-insert-precise-note` and `org-noter-insert-note`. `org-noter-insert-note` is the one who is inserting text after the heading. I'm not sure if there is an easier way to do this (almost sure there is, my elisp isn't that great), but messing a bit with the regular `org-noter-insert-note` function can do what you want. 

I'm not sure on that one, it is a bit late in here and I'm a bit tired. But you probably want to start messing with this `default` value on this line. 
https://github.com/weirdNox/org-noter/blob/9ead81d42dd4dd5074782d239b2efddf9b8b7b3d/org-noter.el#L1801

**Comment by wuqui** [comment]
Thanks for looking into this!

I'm just hesitant to modify this function directly in the package folder because I guess that could cause problems as soon as there's a package update, right?

Maybe this really could be added to the `org-noter`, I'd be surprised if extracting text was not a popular feature for many. It's important anyways, but even more so for me now that I use `org-roam` and turn keywords in the extracted quotes into links to notes, which is really awesome. And `org-roam` is getting really popular, so there should be some demand?

**Comment by seanvert** [comment]
> Thanks for looking into this!
> 
> I'm just hesitant to modify this function directly in the package folder because I guess that could cause problems as soon as there's a package update, right?
> 
> Maybe this really could be added to the `org-noter`, I'd be surprised if extracting text was not a popular feature for many. It's important anyways, but even more so for me now that I use `org-roam` and turn keywords in the extracted quotes into links to notes, which is really awesome. And `org-roam` is getting really popular, so there should be some demand?

Hm, I was really tired yesterday. Definitely making things way harder than they had to be, What you want is quite easy. Just make a keyboard macro, save it into a command and run it after that command.

**Comment by wuqui** [comment]
Ah, so you mean, for example, selecting the region that contains the quote, starting the macro and then deleting the empty line and inserting the block tags; and then just executing  the macro every time I've extracted something, right?

True, that sounds like a good workaround. I don't know how to do that yet, but I'll read up on it and try it soon, thanks!

**Comment by seanvert** [comment]
You have to check it out how it runs, from what I just tested in here you are going to end at the end of the quote. Then you just put a newline write the end of the quote block down, use the search backwards command (I'm not sure but I think it has to be the vanilla one or one of those ivy ones, not sure if it works ok with helm stuff) for the nearest :END:, go to the end of it, break a line, insert the opening quote block and remove the newline. Make a command out of it. Then you can just append it to that old function, inside the `(progn)` sexp. And it will probably work as you want it.

I don't know if it is easier to select the text. But do what you are used to and it will probably work. Emacs macros are great.

**Comment by wuqui** [comment]
Got it running now, thanks again!

For now, I'm doing it the simple way, basically as I indicated above. I manually select the lines I want to be converted and the macro does the rest then. I use `join-line` to "join the lines" by the way, quite handy. I've saved the Macro in my config now, so all good. Again, really surprised that there's not more demand for this, this is a _huge_ gain for my workflow :)

**Comment by bepolymathe** [comment]
Could you be more specific about how you did it? What does the macro look like and how do you integrate it into your config?

**Comment by wuqui** [comment]
Sure. This is what the recorded macro looks like in my config:

```
(fset 'org-noter-wrap-quote
   (kmacro-lambda-form [?  ?: ?j ?o ?i ?n ?e ?  backspace backspace return ?V ?  ?i ?s ?q ?u ?o ?t ?e return escape ?\{ ?\{ ?d ?d] 0 "%d"))
```

I then bind it to a key. Now once I've selected the extracted text, I hit the key (executing `org-noter-wrap-quote`). This 

1. joins the lines
2. converts the region into a block quote
3. removes the blank line

(2) depends on a `yasnippet` that was already available to me because I'm using Doom Emacs. I guess it won't work if you don't have that, but you can easily do it manually and record the macro yourself.

**Comment by bepolymathe** [comment]
Hum.... i have this error `After 0 kbd macro iterations: undefined: Keyboard macro terminated by a command ringing the bell`

I'm bad at macro :cry: 

I have something like that : 

```
(define-key pdf-view-mode-map (kbd "k") 'org-noter-wrap-quote)
 (fset 'org-noter-wrap-quote
       (kmacro-lambda-form [?  ?: ?j ?o ?i ?n ?e ?  backspace backspace return ?V ?  ?i ?s ?q ?u ?o ?t ?e return escape ?\{ ?\{ ?d ?d] 0 "%d"))
```

**Comment by seanvert** [comment]
```elisp
(defun org-noter-insert-selected-text-inside-note-content ()
  (interactive)
  (progn (setq currenb (buffer-name))
		 (org-noter-insert-precise-note)
		 (set-buffer currenb)
		 (org-noter-insert-note)
		 (org-noter-quote) ) )

(fset 'org-noter-quote
   (kmacro-lambda-form [return S-f3 backspace ?# ?+ ?e ?n ?d ?_ ?q ?u ?o ?t ?e ?\C-r ?: ?e return ?\C-e return delete ?# ?+ ?b ?e ?g ?i ?n ?_ ?q ?u ?o ?t ?e] 1 "%d"))

(define-key pdf-view-mode-map (kbd "y") 'org-noter-insert-selected-text-inside-note-content)
```

I made one of these for me, it works on vanilla emacs.

**Comment by wuqui** [comment]
> Hum.... i have this error `After 0 kbd macro iterations: undefined: Keyboard macro terminated by a command ringing the bell`
> 
> I'm bad at macro 😢
> 
> I have something like that :
> 
> ```
> (define-key pdf-view-mode-map (kbd "k") 'org-noter-wrap-quote)
>  (fset 'org-noter-wrap-quote
>        (kmacro-lambda-form [?  ?: ?j ?o ?i ?n ?e ?  backspace backspace return ?V ?  ?i ?s ?q ?u ?o ?t ?e return escape ?\{ ?\{ ?d ?d] 0 "%d"))
> ```

That might be due to all sorts of reasons. @seanvert's new suggestion didn't work for me either. Macros just generally aren't good for sharing.

I would suggest to record one yourself that fits your needs. It's actually quite easy, I hadn't done it before either. Have a look here, for example: https://emacs.stackexchange.com/a/71/29471

**Comment by seanvert** [comment]
https://github.com/weirdNox/org-noter/blob/9ead81d42dd4dd5074782d239b2efddf9b8b7b3d/org-noter.el#L1843, just change it to this 

```elisp
(when (and org-noter-insert-selected-text-inside-note selected-text) (insert (concat "#+begin_quote\n" selected-text "\n#+end_quote"))))
```

I tried changing it when it is defined but dunno why it didn't work, it works fine in here.

**Comment by bepolymathe** [comment]
It’s possible to integrate that in my config without change org-noter.el source ?

**Comment by seanvert** [comment]
> It’s possible to integrate that in my config without change org-noter.el source ?

Yes, but you can change it, no one is going to sue you or anything lol. Just do it, I did it already. Quote blocks on that function defined earlier and you also get quotes when you call it with the regular function (this is how life is supposed to be about lol). It is better than a macro, because mine was bugged when I tried using the same header for multiple quote blocks.

It is not that hard. `C-h f` look for org-noter. Put the cursor on that org-noter.el link, edit the line, and `M-x` `eval-buffer`. Then check it out. Or, if you really don't want to mess with the source, copy the entire org-noter-insert-note function and make another version of it. I honestly prefer this one over the regular because I'm able to differentiate what is yanked and what I wrote down.

**Comment by bepolymathe** [comment]
Hi ! 

Just try now. It works, that’s great. It would be great to have lines joined too... but it’s not a big deal. 
See you.

**Comment by bepolymathe** [comment]
Hi, 

I’am try to have the same behaviour on a new machine and with the useful [Org-pdftools](https://github.com/fuxialexander/org-pdftools). But it seems don’t work...

**Comment by seanvert** [comment]
> Hi,
> 
> I’am try to have the same behaviour on a new machine and with the useful [Org-pdftools](https://github.com/fuxialexander/org-pdftools). But it seems don’t work...

You have to check out what org-noter function does it call when it inserts its links. How are you using org-pdftools?
