### ISSUE TITLE
org-noter-create-skeleton not producing outlines on some pdf files

### ISSUE THREAD

**Issue by Raqato** [weirdNox/org-noter#95]
Hello, 
I'm using org-noter in doom-emacs. I'm having troubles while generating outlines using org-noter-create-skeleton for some pdf files. I have atttached one such pdf here. 
[pruett2000.pdf](https://github.com/weirdNox/org-noter/files/4186951/pruett2000.pdf)

My config for org-noter is pretty basic.
```
(use-package! org-noter
  :after org
  :config (setq org-noter-notes-search-path '("~/org")))
```
This is how I'm running org-noter:
Open the pdf file in emacs and run org-noter, following this I run org-noter-create-skeleton and the org file remains unchanged. I followed the workflow from a youtube video by @fuxialexander [here](https://www.youtube.com/watch?v=lCc3UoQku-E&feature=emb_title)

**Comment by smallzhan** [comment]
@Raqato  There are no outline for some pdf files, including your file.  You can just open the file in emacs with `pdf-tools',  and print `o',  if no outline, a message would show in minibuffer.

**Comment by Raqato** [comment]
Thank you that makes total sense. I hadn't realised such a simple thing. I just learned how exactly org-noter-create-skeleton is working. I will close this issue as it is an issue with the pdf files themselves and not how a skeleton is being produced. The pdf files themselves do not contain any outline info.
